run:
  allow-parallel-runners: true

issues:
  exclude-dirs:
    - vendor
    - .git
    - .idea
    - dist
    - .github
    - resources
    - bin
    - internal/data
  exclude-rules:
    - path: 'pkg/connection/connection.go'
      linters:
        - dupl
    - path: (.+)_test.go
      linters:
        - gosec
        - dupl

linters:
  disable:
    - scopelint
    - goerr113
    - err113
    - mnd
    - wrapcheck
    - funlen
    - maligned
    - golint
    - interfacer
    - gomnd
    - gochecknoglobals
    - exhaustivestruct
    - lll
    - wsl
    - thelper
    - testpackage
    - typecheck
    - nlreturn
    - nilnil
    - varnamelen
    - forcetypeassert
    - exhaustruct
    - gocognit
    - tagliatelle
    - ifshort
    - forbidigo
    - musttag
    - interfacebloat
    - cyclop
    - tparallel
    - depguard
    - tagalign
    - gocyclo
    - exportloopref
  presets:
    - bugs
    - comment
    - complexity
    - error
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
linters-settings:
  revive:
    rules:
      - name: unexported-return
        disabled: true
  maintidx:
    under: 10

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - (or|er)$
      - bigquery.DB
      - snowflake.SfClient
      - postgres.PgClient
      - mssql.MsClient
      - databricks.Client
      - athena.Client
  goconst:
    min-len: 5
    min-occurrences: 5
  nestif:
    min-complexity: 10
  testifylint:
    enable:
      - "bool-compare"
      - "compares"
      - "empty"
      - "error-is-as"
      - "error-nil"
      - "expected-actual"
      - "float-compare"
      - "len"
      - "suite-dont-use-pkg"
      - "suite-extra-assert-call"
      - "suite-thelper"

  gosec:
    excludes:
      - G601