version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: bruin-darwin
    binary: bruin
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}
    main: ./
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_ENABLED=1
    flags:
      - -trimpath
 
  - id: bruin-linux-amd64
    binary: bruin
    main: ./
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
  - id: bruin-linux-arm64
    binary: bruin
    main: ./
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
  - id: bruin-windows-amd64
    binary: bruin
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
    flags:
      - -trimpath
      - -buildmode=exe


archives:
  - format: tar.gz
    builds:
      - bruin-linux-arm64
      - bruin-linux-amd64
      - bruin-darwin
      - bruin-windows-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"



nfpms:
  - package_name: bruin
    homepage: https://getbruin.com
    maintainer: Burak Karakan <burak.karakan@getbruin.com>
    description: "Bruin is a command-line tool for validating and running data transformations on SQL and Python."
    vendor: Bruin Data
    license: MIT
    formats:
      - apk
      - deb
    dependencies:
      - git