version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: bruin-darwin
    binary: bruin
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}
    main: ./
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
    flags:
    - -trimpath
    - -buildmode=pie
    env:
    - CGO_ENABLED=1
    - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=zig c -target x86_64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
        {{- end }}
    - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=zig c++ -target x86_64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-macos-none -F{{ .Env.SDK_PATH }}/System/Library/Frameworks{{- end }}
        {{- end }}
 
  - id: bruin-linux
    binary: bruin
    main: ./
    goarch:
      - arm64
      - amd64
    goos:
      - linux
    flags:
    - -trimpath
    env:
    - CGO_ENABLED=1
    - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=zig c -target x86_64-linux-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-linux-musl{{- end }}
        {{- end }}
    - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=zig c++ -target x86_64-linux-musl{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-linux-musl{{- end }}
        {{- end }}
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
  - id: bruin-windows
    binary: bruin
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
    flags:
    - -trimpath
    env:
    - CGO_ENABLED=1
    - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=zig c -target x86_64-windows-gnu{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig c -target aarch64-windows-gnu{{- end }}
        {{- end }}
    - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=zig c++ -target x86_64-windows-gnu{{- end }}
          {{- if eq .Arch "arm64"}}CC=zig c++ -target aarch64-windows-gnu{{- end }}
        {{- end }}


archives:
  - format: tar.gz
    builds:
      - bruin-linux
      - bruin-darwin
      - bruin-windows
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# .goreleaser.yaml
brews:
  - name: bruin

    # Git author used to commit to the repository.
    commit_author:
      name: karakanb
      email: burak.karakan@getbruin.com

    # Folder inside the repository to put the formula.
    directory: Formula

    # The project name and current git tag are used in the format string.
    #
    # Templates: allowed
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Your app's homepage.
    homepage: "https://getbruin.com"
    description: "Bruin is a command-line tool for validating and running data transformations on SQL and Python."

    dependencies:
      - name: git

    repository:
      owner: bruin-data
      name: homebrew-tap

nfpms:
  - package_name: bruin
    homepage: https://getbruin.com
    maintainer: Burak Karakan <burak.karakan@getbruin.com>
    description: "Bruin is a command-line tool for validating and running data transformations on SQL and Python."
    vendor: Bruin Data
    license: MIT
    formats:
      - apk
      - deb
    dependencies:
      - git


