name: enabled-template-pipeline
default_connections:
  duckdb: duckdb-default
variables:
  upstream_enabled:
    type: boolean
    default: true
variants:
  disabled:
    upstream_enabled: false
  enabled:
    upstream_enabled: true
