"""Generates Go tables for pkg/sqlglot from a pinned sqlglot installation.

The Go package is a port of sqlglot. Everything that is pure data in sqlglot (token
types, expression class metadata, data types, dialect/tokenizer/parser/generator
settings) is generated here from the live Python objects so the Go port cannot drift
from the reference implementation. Procedural code is ported by hand.

Usage: python gen.py <output-dir>
"""

from __future__ import annotations

import enum
import inspect
import os
import subprocess
import re
import sys
import types
import typing as t

import sqlglot
from sqlglot import exp
from sqlglot.dialects.dialect import Dialect, NormalizationStrategy
from sqlglot.generator import Generator
from sqlglot.parser import Parser
from sqlglot.tokens import Tokenizer, TokenType

SQLGLOT_VERSION = sqlglot.__version__
assert SQLGLOT_VERSION == "30.13.0", SQLGLOT_VERSION

OUT = sys.argv[1] if len(sys.argv) > 1 else "."

DIALECTS = [
    "",
    "athena",
    "bigquery",
    "clickhouse",
    "databricks",
    "doris",
    "duckdb",
    "fabric",
    "hive",
    "mysql",
    "oracle",
    "postgres",
    "presto",
    "redshift",
    "snowflake",
    "spark",
    "spark2",
    "sqlite",
    "starrocks",
    "trino",
    "tsql",
]

HEADER = (
    "// Code generated by pkg/sqlengine/codegen/gen.py from sqlglot %s. DO NOT EDIT.\n\n"
    "package sqlengine\n\n" % SQLGLOT_VERSION
)


WRITTEN: list[str] = []


def write(name: str, body: str) -> None:
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write(HEADER + body)
    WRITTEN.append(path)


def gostr(s: str) -> str:
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F:
            out.append("\\x%02x" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


# ---------------------------------------------------------------------------
# Token types
# ---------------------------------------------------------------------------

TOKEN_TYPES = list(TokenType)


def tok(tt: TokenType) -> str:
    return "TK_" + tt.name


def gen_tokens() -> None:
    lines = ["// TokenType mirrors sqlglot.tokens.TokenType.\ntype TokenType uint16\n\nconst (\n"]
    lines.append("\tTK_NONE TokenType = 0\n")
    for tt in TOKEN_TYPES:
        lines.append("\t%s TokenType = %d\n" % (tok(tt), tt.value))
    lines.append(")\n\nconst numTokenTypes = %d\n\n" % (max(t.value for t in TOKEN_TYPES) + 1))
    lines.append("var tokenTypeNames = [numTokenTypes]string{\n")
    for tt in TOKEN_TYPES:
        lines.append("\t%s: %s,\n" % (tok(tt), gostr(tt.name)))
    lines.append("}\n")
    write("zz_tokens.go", "".join(lines))


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

DTYPES = list(exp.DType)


def dt(d) -> str:
    return "DT_" + d.name


def gen_dtypes() -> None:
    lines = ["// DType mirrors sqlglot.expressions.DataType.Type.\ntype DType uint16\n\nconst (\n"]
    lines.append("\tDT_NONE DType = 0\n")
    for i, d in enumerate(DTYPES):
        lines.append("\t%s DType = %d\n" % (dt(d), i + 1))
    lines.append(")\n\nconst numDTypes = %d\n\n" % (len(DTYPES) + 1))
    lines.append("var dtypeNames = [numDTypes]string{\n")
    for d in DTYPES:
        lines.append("\t%s: %s,\n" % (dt(d), gostr(d.name)))
    lines.append("}\n\nvar dtypeValues = [numDTypes]string{\n")
    for d in DTYPES:
        lines.append("\t%s: %s,\n" % (dt(d), gostr(d.value)))
    lines.append("}\n\n")
    for attr in sorted(vars(exp.DataType)):
        v = getattr(exp.DataType, attr)
        if attr.isupper() and isinstance(v, (set, frozenset)):
            lines.append(
                "var DataType_%s = newDTypeSet(%s)\n" % (attr, ", ".join(dt(x) for x in sorted(v, key=lambda x: x.name)))
            )
    write("zz_dtypes.go", "".join(lines))


# ---------------------------------------------------------------------------
# Expression classes
# ---------------------------------------------------------------------------


def all_expr_classes() -> list[type]:
    seen: dict[str, type] = {"Expr": exp.Expr}

    def walk(c):
        for s in c.__subclasses__():
            if s.__name__ not in seen:
                seen[s.__name__] = s
            walk(s)

    walk(exp.Expr)
    # Stable order: definition order by module/line keeps related kinds together.
    def key(c):
        try:
            return (c.__module__, inspect.getsourcelines(c)[1])
        except (OSError, TypeError):
            return (c.__module__, 0)

    return sorted(seen.values(), key=key)


EXPR_CLASSES = all_expr_classes()
KIND_OF = {c: "K" + c.__name__ for c in EXPR_CLASSES}


def kind(c) -> str:
    return KIND_OF[c]


def gen_kinds() -> None:
    lines = ["// Kind identifies a sqlglot expression class.\ntype Kind uint16\n\nconst (\n"]
    lines.append("\tKNone Kind = 0\n")
    for i, c in enumerate(EXPR_CLASSES):
        lines.append("\t%s Kind = %d\n" % (kind(c), i + 1))
    lines.append(")\n\nconst numKinds = %d\n\n" % (len(EXPR_CLASSES) + 1))
    lines.append("var kindInfos = [numKinds]kindInfo{\n")
    for c in EXPR_CLASSES:
        mro = [kind(b) for b in c.__mro__ if b in KIND_OF]
        args = ", ".join("{%s, %s}" % (gostr(k), "true" if v else "false") for k, v in c.arg_types.items())
        flags = []
        for flag in ("is_var_len_args", "_hash_raw_args", "is_subquery", "is_cast", "is_data_type", "is_primitive"):
            if getattr(c, flag, False):
                flags.append({"is_var_len_args": "kfVarLenArgs", "_hash_raw_args": "kfHashRawArgs",
                              "is_subquery": "kfSubquery", "is_cast": "kfCast", "is_data_type": "kfDataType",
                              "is_primitive": "kfPrimitive"}[flag])
        sql_names = []
        if issubclass(c, exp.Func) and c is not exp.Func:
            try:
                sql_names = c.sql_names()
            except Exception:
                sql_names = []
        lines.append(
            "\t%s: {name: %s, module: %s, key: %s, mro: []Kind{%s}, args: []argSpec{%s}, flags: %s, sqlNames: []string{%s}},\n"
            % (
                kind(c),
                gostr(c.__name__),
                gostr(c.__module__.rsplit(".", 1)[-1]),
                gostr(c.key),
                ", ".join(mro),
                args,
                " | ".join(flags) if flags else "0",
                ", ".join(gostr(n) for n in sql_names),
            )
        )
    lines.append("}\n\n")
    # name lookup tables
    lines.append("var kindByKey = map[string]Kind{\n")
    for c in EXPR_CLASSES:
        if c is exp.Expr:
            continue
        lines.append("\t%s: %s,\n" % (gostr(c.key), kind(c)))
    lines.append("}\n\n")
    # FUNCTION_BY_NAME
    lines.append("// FUNCTION_BY_NAME mirrors sqlglot.expressions.FUNCTION_BY_NAME.\nvar FUNCTION_BY_NAME = map[string]Kind{\n")
    for name, c in sorted(exp.FUNCTION_BY_NAME.items()):
        lines.append("\t%s: %s,\n" % (gostr(name), kind(c)))
    lines.append("}\n\n")
    lines.append("// ALL_FUNCTIONS mirrors sqlglot.expressions.ALL_FUNCTIONS.\nvar ALL_FUNCTIONS = []Kind{%s}\n\n" % ", ".join(kind(c) for c in exp.ALL_FUNCTIONS))
    write("zz_kinds.go", "".join(lines))


# ---------------------------------------------------------------------------
# Generic value conversion for dialect tables
# ---------------------------------------------------------------------------


class Unsupported(Exception):
    pass


def classify(v):
    """Returns (go_type, go_literal) for a data value, or raises Unsupported."""
    if isinstance(v, bool):
        return "bool", "true" if v else "false"
    if isinstance(v, enum.Enum) and isinstance(v, TokenType):
        return "TokenType", tok(v)
    if isinstance(v, exp.DType):
        return "DType", dt(v)
    if isinstance(v, enum.Enum):
        return "string", gostr(str(v.value))
    if isinstance(v, int):
        return "int", str(v)
    if isinstance(v, str):
        return "string", gostr(v)
    if v is None:
        return "nil", "nil"
    if isinstance(v, type) and v in KIND_OF:
        return "Kind", kind(v)
    if isinstance(v, (set, frozenset)):
        if not v:
            return "emptyset", ""
        sample = next(iter(v))
        if isinstance(sample, TokenType):
            return "TokenSet", "newTokenSet(%s)" % ", ".join(tok(x) for x in sorted(v, key=lambda x: x.value))
        if isinstance(sample, exp.DType):
            return "DTypeSet", "newDTypeSet(%s)" % ", ".join(dt(x) for x in sorted(v, key=lambda x: x.name))
        if isinstance(sample, str):
            return "StrSet", "newStrSet(%s)" % ", ".join(gostr(x) for x in sorted(v))
        if isinstance(sample, type) and sample in KIND_OF:
            return "KindSet", "newKindSet(%s)" % ", ".join(kind(x) for x in sorted(v, key=lambda x: x.__name__))
        raise Unsupported("set of %r" % type(sample))
    if isinstance(v, tuple) and len(v) == 2 and isinstance(v[0], str) and isinstance(v[1], TokenType):
        return "formatString", "formatString{%s, %s}" % (gostr(v[0]), tok(v[1]))
    if isinstance(v, (tuple, list)):
        if not v:
            return "emptylist", ""
        if all(isinstance(x, TokenType) for x in v):
            return "[]TokenType", "[]TokenType{%s}" % ", ".join(tok(x) for x in v)
        if all(isinstance(x, int) and not isinstance(x, (bool, enum.Enum)) for x in v):
            return "[]int", "[]int{%s}" % ", ".join(str(x) for x in v)
        if all(isinstance(x, (tuple, list)) and all(isinstance(y, int) for y in x) for x in v):
            return "[][]int", "[][]int{%s}" % ", ".join("{%s}" % ", ".join(str(y) for y in x) for x in v)
        if all(isinstance(x, type) and x in KIND_OF for x in v):
            return "[]Kind", "[]Kind{%s}" % ", ".join(kind(x) for x in v)
        if all(isinstance(x, str) for x in v):
            return "[]string", "[]string{%s}" % ", ".join(gostr(x) for x in v)
        if all(isinstance(x, TokenType) for x in v):
            return "[]TokenType", "[]TokenType{%s}" % ", ".join(tok(x) for x in v)
        if all(isinstance(x, (tuple, list)) and all(isinstance(y, str) for y in x) and len(x) == 2 for x in v):
            return "[][2]string", "[][2]string{%s}" % ", ".join("{%s, %s}" % (gostr(a), gostr(b)) for a, b in v)
        if all(isinstance(x, (str, tuple)) for x in v):
            # mixed list of str | (str, str) as used by QUOTES/IDENTIFIERS etc.
            parts = []
            for x in v:
                if isinstance(x, str):
                    parts.append("{%s, %s}" % (gostr(x), '""'))
                else:
                    parts.append("{%s, %s}" % (gostr(x[0]), gostr(x[1])))
            return "[][2]string", "[][2]string{%s}" % ", ".join(parts)
        raise Unsupported("list of %r" % [type(x) for x in v])
    if isinstance(v, dict):
        if not v:
            return "emptydict", ""
        items = list(v.items())
        if all(isinstance(k, str) for k in v) and all(
            isinstance(val, (tuple, list)) and all(isinstance(x, str) or (isinstance(x, (tuple, list)) and all(isinstance(y, str) for y in x)) for x in val)
            for val in v.values()
        ) and any(isinstance(x, (tuple, list)) for val in v.values() for x in val) or (
            all(isinstance(k, str) for k in v) and all(isinstance(val, (tuple, list)) and all(isinstance(x, str) for x in val) for val in v.values()) and any(isinstance(val, tuple) for val in v.values())
        ):
            entries = []
            for k, val in items:
                opts = []
                for x in val:
                    words = [x] if isinstance(x, str) else list(x)
                    opts.append("{%s}" % ", ".join(gostr(w) for w in words))
                entries.append("%s: {%s}" % (gostr(k), ", ".join(opts)))
            return "OptionsType", "OptionsType{%s}" % ", ".join(entries)
        kts = {classify_key(k) for k, _ in items}
        if len(kts) != 1:
            raise Unsupported("mixed dict keys %r" % kts)
        kt = kts.pop()
        vals = []
        vts = set()
        for k, val in items:
            try:
                vt, vl = classify(val)
            except Unsupported:
                raise
            vts.add(vt)
            vals.append((k, vt, vl))
        had_nil = "nil" in vts
        vts.discard("nil")
        if had_nil and vts == {"bool"}:
            vts = {"Tri"}
            vals = [(k, "Tri", {"nil": "TriNone", "true": "TriTrue", "false": "TriFalse"}[vl]) for k, _vt, vl in vals]
        if len(vts) > 1:
            if vts <= {"emptyset", "StrSet"}:
                vts = {"StrSet"}
            elif vts <= {"emptylist", "[]string"}:
                vts = {"[]string"}
            elif vts <= {"emptylist", "[][]string", "[]string"}:
                vts = {"[][]string"}
            else:
                raise Unsupported("mixed dict values %r" % vts)
        vt = vts.pop() if vts else "nil"
        if vt == "emptyset":
            vt = "StrSet"
        if vt == "emptylist":
            vt = "[]string"
        kgo, keylit = kt
        entries = []
        zero = {"string": '""', "Kind": "KNone", "TokenType": "TK_NONE", "DType": "DT_NONE", "int": "0", "bool": "false"}
        for k, _vt, vl in vals:
            if vl == "nil" and vt in zero:
                vl = zero[vt]
            if vl == "" and _vt in ("emptyset",):
                vl = "newStrSet()"
            if vl == "" and _vt in ("emptylist",):
                vl = "nil"
            entries.append("%s: %s" % (keylit(k), vl))
        gotype = "map[%s]%s" % (kgo, gotypename(vt))
        return gotype, "%s{%s}" % (gotype, ", ".join(entries))
    if callable(v):
        raise Unsupported("callable")
    raise Unsupported(repr(type(v)))


def gotypename(vt: str) -> str:
    return {"nil": "any"}.get(vt, vt)


def classify_key(k):
    if isinstance(k, TokenType):
        return ("TokenType", tok)
    if isinstance(k, exp.DType):
        return ("DType", dt)
    if isinstance(k, str):
        return ("string", gostr)
    if isinstance(k, type) and k in KIND_OF:
        return ("Kind", kind)
    if isinstance(k, enum.Enum):
        return ("string", lambda x: gostr(str(x.value)))
    if isinstance(k, bool):
        return ("bool", lambda x: "true" if x else "false")
    raise Unsupported("key %r" % type(k))


def class_data_attrs(cls, base) -> dict:
    """All upper-case data attributes visible on cls (including inherited)."""
    out = {}
    for name in dir(cls):
        if not name.isupper() and not (name.startswith("_") and name[1:].isupper()):
            continue
        if name.startswith("__"):
            continue
        try:
            v = getattr(cls, name)
        except Exception:
            continue
        if inspect.isclass(v) and not (v in KIND_OF):
            continue
        out[name] = v
    return out


def dialect_class(name: str):
    return Dialect.get_or_raise(name).__class__


def go_dialect_id(name: str) -> str:
    return name or "base"


def emit_settings_struct(struct_name: str, per_dialect: dict[str, dict], skip=()) -> tuple[str, dict[str, str], list[str]]:
    """Builds a struct type with one field per attribute and returns field go types."""
    field_types: dict[str, str] = {}
    unsupported: list[str] = []
    seen_nil: set[str] = set()
    for d, attrs in per_dialect.items():
        for name, v in attrs.items():
            if name in skip:
                continue
            try:
                gt, _ = classify(v)
            except Exception as e:
                if not isinstance(e, Unsupported):
                    print("warning: %s.%s: %r" % (struct_name, name, e), file=sys.stderr)
                if name not in unsupported:
                    unsupported.append(name)
                continue
            if gt == "nil":
                seen_nil.add(name)
            prev = field_types.get(name)
            if prev is None or prev in ("nil", "emptyset", "emptylist", "emptydict"):
                field_types[name] = gt
            elif gt in ("nil", "emptyset", "emptylist", "emptydict") or gt == prev:
                pass
            elif {prev, gt} <= {"[]string", "[][2]string"}:
                field_types[name] = "[][2]string"
            elif prev.startswith("map[") and gt.startswith("map[") and prev.split("]")[0] == gt.split("]")[0] and {prev.split("]",1)[1], gt.split("]",1)[1]} <= {"bool", "Tri", "any"}:
                field_types[name] = prev.split("]")[0] + "]Tri"
            elif "OptionsType" in (prev, gt) and {prev, gt} - {"OptionsType"} <= {"emptydict", "map[string][]string"}:
                field_types[name] = "OptionsType"
            elif {prev, gt} <= {"string", "bool"}:
                # e.g. NORMALIZE_FUNCTIONS: "upper" | "lower" | False. False -> "", True -> "true".
                field_types[name] = "string"
            else:
                raise SystemExit("type conflict for %s.%s: %s vs %s" % (struct_name, name, prev, gt))
    for name in list(field_types):
        if name in unsupported:
            del field_types[name]
        elif field_types[name] == "bool" and name in seen_nil:
            field_types[name] = "Tri"
    out = ["type %s struct {\n" % struct_name]
    for name in sorted(field_types):
        gt = field_types[name]
        out.append("\t%s %s\n" % (name, go_field_type(gt)))
    out.append("}\n\n")
    return "".join(out), field_types, unsupported


def go_field_type(gt: str) -> str:
    return {
        "nil": "any",
        "emptyset": "StrSet",
        "emptylist": "[]string",
        "emptydict": "map[string]string",
    }.get(gt, gt)



def literal_for(gt: str, v) -> str:
    if gt == "Tri":
        return "TriNone" if v is None else ("TriTrue" if v else "TriFalse")
    if gt == "string" and isinstance(v, bool):
        return gostr("true") if v else '""'
    vt, vl = classify(v)
    if vt == "nil":
        if gt in ("string",):
            return '""'
        if gt == "bool":
            return "false"
        if gt == "int":
            return "0"
        if gt in ("TokenType",):
            return "TK_NONE"
        if gt == "DType":
            return "DT_NONE"
        if gt == "Kind":
            return "KNone"
        return "nil"
    if vt == "emptyset":
        return {"TokenSet": "newTokenSet()", "DTypeSet": "newDTypeSet()", "StrSet": "newStrSet()", "KindSet": "newKindSet()"}.get(gt, "newStrSet()")
    if vt == "emptylist":
        return "nil"
    if vt == "emptydict":
        return "%s{}" % go_field_type(gt)
    if vt == "[]string" and gt == "[][2]string":
        return "[][2]string{%s}" % ", ".join("{%s, %s}" % (gostr(x), gostr(x)) for x in v)
    if gt.endswith("]Tri") and (vt.endswith("]bool") or vt.endswith("]any")):
        vl = vl.replace(": nil", ": TriNone")
        vl = vl.replace(": true", ": TriTrue").replace(": false", ": TriFalse")
        return gt + vl[vl.index("{"):]
    if vt != gt and gt.startswith("map[") and vt.startswith("map["):
        # re-emit with declared type
        return gt + vl[vl.index("{"):]
    return vl


def gen_settings(kind_name: str, struct_name: str, getter, filename: str, skip=()) -> dict:
    per_dialect = {}
    for d in DIALECTS:
        cls = getter(d)
        per_dialect[d] = class_data_attrs(cls, None)
    struct, field_types, unsupported = emit_settings_struct(struct_name, per_dialect, skip)
    body = [struct]
    for d in DIALECTS:
        attrs = per_dialect[d]
        body.append("func %s_%s() *%s {\n\treturn &%s{\n" % (kind_name, go_dialect_id(d), struct_name, struct_name))
        for name in sorted(field_types):
            if name not in attrs:
                continue
            lit = literal_for(field_types[name], attrs[name])
            body.append("\t\t%s: %s,\n" % (name, lit))
        body.append("\t}\n}\n\n")
    if unsupported:
        body.append("// Not generated (callable or unsupported values):\n")
        for name in sorted(unsupported):
            body.append("//   %s\n" % name)
    write(filename, "".join(body))
    return per_dialect


PROPS = [
    "name", "output_name", "is_star", "alias_or_name", "selects", "named_selects", "parts", "this",
    "to_py", "is_type", "unnest", "ctes", "kind", "side", "left", "right", "select", "unit", "alias",
    "table", "db", "catalog", "key", "is_string", "expressions",
]


def gen_props() -> None:
    lines = ["// propOwner_X[k] is the class (first in k's MRO) that defines property X, or KNone when\n"
             "// it is the Expression default.\n"]
    for prop in PROPS:
        entries = []
        for c in EXPR_CLASSES:
            owner = None
            for b in c.__mro__:
                if prop in b.__dict__:
                    owner = b
                    break
            if owner is None or owner in (exp.Expr, exp.Expression):
                continue
            entries.append("\t%s: %s,\n" % (kind(c), kind(owner)))
        lines.append("var propOwner_%s = [numKinds]Kind{\n%s}\n\n" % (prop, "".join(entries)))
    write("zz_props.go", "".join(lines))


def gen_unicode() -> None:
    up, low = [], []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        u, l = c.upper(), c.lower()
        if u != c:
            up.append((cp, u))
        if l != c:
            low.append((cp, l))
    lines = ["// Python str.upper()/str.lower() per code point (only entries that change).\n"]
    lines.append("var pyUpperMap = map[rune]string{\n")
    for cp, u in up:
        lines.append("\t0x%X: %s,\n" % (cp, gostr(u)))
    lines.append("}\n\nvar pyLowerMap = map[rune]string{\n")
    for cp, l in low:
        lines.append("\t0x%X: %s,\n" % (cp, gostr(l)))
    lines.append("}\n")
    write("zz_unicode.go", "".join(lines))


def gen_exp_constants() -> None:
    P = exp.Properties
    lines = ["// Properties.NAME_TO_PROPERTY / PROPERTY_TO_NAME.\nvar NAME_TO_PROPERTY = map[string]Kind{\n"]
    for k, v in P.NAME_TO_PROPERTY.items():
        lines.append("\t%s: %s,\n" % (gostr(k), kind(v)))
    lines.append("}\n\nvar PROPERTY_TO_NAME = map[Kind]string{\n")
    for k, v in P.PROPERTY_TO_NAME.items():
        lines.append("\t%s: %s,\n" % (kind(k), gostr(v)))
    lines.append("}\n\n// Properties.Location values.\nconst (\n")
    for loc in P.Location:
        lines.append("\tLoc_%s = %s\n" % (loc.name, gostr(loc.value)))
    lines.append(")\n\n")
    lines.append("// Locations in definition order.\nvar PropertiesLocations = []string{%s}\n\n" % ", ".join(gostr(l.value) for l in P.Location))
    lines.append("// QUERY_MODIFIERS mirrors exp.QUERY_MODIFIERS (ordered).\nvar QUERY_MODIFIERS = []string{%s}\n\n" % ", ".join(gostr(k) for k in exp.QUERY_MODIFIERS))
    lines.append("var TABLE_PARTS = []string{%s}\nvar COLUMN_PARTS = []string{%s}\n" % (", ".join(gostr(x) for x in exp.TABLE_PARTS), ", ".join(gostr(x) for x in exp.COLUMN_PARTS)))
    write("zz_exp_constants.go", "".join(lines))


def main() -> None:
    gen_exp_constants()
    gen_unicode()
    gen_props()
    gen_tokens()
    gen_dtypes()
    gen_kinds()
    gen_settings("tokenizerSettings", "TokenizerSettings", lambda d: dialect_class(d).tokenizer_class, "zz_tokenizer_settings.go")
    gen_settings("dialectSettings", "DialectSettings", lambda d: dialect_class(d), "zz_dialect_settings.go")
    gen_settings("parserSettings", "ParserData", lambda d: dialect_class(d).parser_class, "zz_parser_settings.go")
    gen_settings("generatorSettings", "GeneratorData", lambda d: dialect_class(d).generator_class, "zz_generator_settings.go")
    # Same formatter as `make format` (run from the Bruin repository root).
    subprocess.run(["go", "tool", "gofumpt", "-w", *WRITTEN], check=True)


if __name__ == "__main__":
    main()
