# Zoomcamp template: pipeline.yml
# Goal: help you learn Bruin pipeline configuration patterns. This file is intentionally *not* runnable until you complete the TODOs.
#
# Key docs:
# - Pipeline files: https://getbruin.com/docs/bruin/getting-started/pipeline
# - Variables (JSON Schema): https://getbruin.com/docs/bruin/getting-started/pipeline-variables
# - Run command: https://getbruin.com/docs/bruin/commands/run

# TODO: Set a pipeline name (string). This shows up in logs + `BRUIN_PIPELINE` for Python assets.
name: TODO_SET_PIPELINE_NAME

# TODO: Pick a schedule ("daily", "hourly", "weekly", "monthly") or a cron string.
schedule: TODO_SET_SCHEDULE

# TODO: Set the earliest date this pipeline should consider for full refresh backfills.
# Format: YYYY-MM-DD
start_date: "TODO_SET_START_DATE"

# TODO: Configure default connections so assets can omit explicit `connection: ...`.
# Common pattern: `duckdb: duckdb-default` for local dev.
# Docs (connections): https://getbruin.com/docs/bruin/commands/connections
default_connections:
  duckdb: TODO_CONNECTION_NAME

# TODO: Define pipeline variables using JSON Schema and defaults.
# - Variables must have a `default` so assets can render without `--var`.
# - In SQL/YAML assets: reference as `{{ var.my_variable }}`.
# - In Python assets: read JSON from env var `BRUIN_VARS`.
variables:
  # TODO: Define `taxi_types` as an array of strings with a sensible default.
  taxi_types:
    type: TODO  # should be: array
    items:
      type: TODO  # should be: string
    default: TODO  # e.g. ["yellow", "green"]
#   other_string_var: (optional) Add your own variable and use it in both Python and SQL assets.
#     type: string
#     default: "my_value"
