// Code generated by pkg/sqlengine/codegen/gen.py from sqlglot 30.13.0. DO NOT EDIT.

package sqlengine

// DType mirrors sqlglot.expressions.DataType.Type.
type DType uint16

const (
	DT_NONE                    DType = 0
	DT_ARRAY                   DType = 1
	DT_AGGREGATEFUNCTION       DType = 2
	DT_SIMPLEAGGREGATEFUNCTION DType = 3
	DT_BIGDECIMAL              DType = 4
	DT_BIGINT                  DType = 5
	DT_BIGNUM                  DType = 6
	DT_BIGSERIAL               DType = 7
	DT_BINARY                  DType = 8
	DT_BIT                     DType = 9
	DT_BLOB                    DType = 10
	DT_BOOLEAN                 DType = 11
	DT_BPCHAR                  DType = 12
	DT_CHAR                    DType = 13
	DT_CHARACTER_SET           DType = 14
	DT_DATE                    DType = 15
	DT_DATE32                  DType = 16
	DT_DATEMULTIRANGE          DType = 17
	DT_DATERANGE               DType = 18
	DT_DATETIME                DType = 19
	DT_DATETIME2               DType = 20
	DT_DATETIME64              DType = 21
	DT_DECIMAL                 DType = 22
	DT_DECIMAL32               DType = 23
	DT_DECIMAL64               DType = 24
	DT_DECIMAL128              DType = 25
	DT_DECIMAL256              DType = 26
	DT_DECFLOAT                DType = 27
	DT_DOUBLE                  DType = 28
	DT_DYNAMIC                 DType = 29
	DT_ENUM                    DType = 30
	DT_ENUM8                   DType = 31
	DT_ENUM16                  DType = 32
	DT_FILE                    DType = 33
	DT_FIXEDSTRING             DType = 34
	DT_FLOAT                   DType = 35
	DT_GEOGRAPHY               DType = 36
	DT_GEOGRAPHYPOINT          DType = 37
	DT_GEOMETRY                DType = 38
	DT_POINT                   DType = 39
	DT_RING                    DType = 40
	DT_LINESTRING              DType = 41
	DT_MULTILINESTRING         DType = 42
	DT_POLYGON                 DType = 43
	DT_MULTIPOLYGON            DType = 44
	DT_HLLSKETCH               DType = 45
	DT_HSTORE                  DType = 46
	DT_IMAGE                   DType = 47
	DT_INET                    DType = 48
	DT_INT                     DType = 49
	DT_INT128                  DType = 50
	DT_INT256                  DType = 51
	DT_INT4MULTIRANGE          DType = 52
	DT_INT4RANGE               DType = 53
	DT_INT8MULTIRANGE          DType = 54
	DT_INT8RANGE               DType = 55
	DT_INTERVAL                DType = 56
	DT_IPADDRESS               DType = 57
	DT_IPPREFIX                DType = 58
	DT_IPV4                    DType = 59
	DT_IPV6                    DType = 60
	DT_JSON                    DType = 61
	DT_JSONB                   DType = 62
	DT_LIST                    DType = 63
	DT_LONGBLOB                DType = 64
	DT_LONGTEXT                DType = 65
	DT_LOWCARDINALITY          DType = 66
	DT_MAP                     DType = 67
	DT_MEDIUMBLOB              DType = 68
	DT_MEDIUMINT               DType = 69
	DT_MEDIUMTEXT              DType = 70
	DT_MONEY                   DType = 71
	DT_NAME                    DType = 72
	DT_NCHAR                   DType = 73
	DT_NESTED                  DType = 74
	DT_NOTHING                 DType = 75
	DT_NULL                    DType = 76
	DT_NUMMULTIRANGE           DType = 77
	DT_NUMRANGE                DType = 78
	DT_NVARCHAR                DType = 79
	DT_OBJECT                  DType = 80
	DT_RANGE                   DType = 81
	DT_ROWVERSION              DType = 82
	DT_SERIAL                  DType = 83
	DT_SET                     DType = 84
	DT_SMALLDATETIME           DType = 85
	DT_SMALLINT                DType = 86
	DT_SMALLMONEY              DType = 87
	DT_SMALLSERIAL             DType = 88
	DT_STRUCT                  DType = 89
	DT_SUPER                   DType = 90
	DT_TEXT                    DType = 91
	DT_TINYBLOB                DType = 92
	DT_TINYTEXT                DType = 93
	DT_TIME                    DType = 94
	DT_TIMETZ                  DType = 95
	DT_TIME_NS                 DType = 96
	DT_TIMESTAMP               DType = 97
	DT_TIMESTAMPNTZ            DType = 98
	DT_TIMESTAMPLTZ            DType = 99
	DT_TIMESTAMPTZ             DType = 100
	DT_TIMESTAMP_S             DType = 101
	DT_TIMESTAMP_MS            DType = 102
	DT_TIMESTAMP_NS            DType = 103
	DT_TINYINT                 DType = 104
	DT_TSMULTIRANGE            DType = 105
	DT_TSRANGE                 DType = 106
	DT_TSTZMULTIRANGE          DType = 107
	DT_TSTZRANGE               DType = 108
	DT_UBIGINT                 DType = 109
	DT_UINT                    DType = 110
	DT_UINT128                 DType = 111
	DT_UINT256                 DType = 112
	DT_UMEDIUMINT              DType = 113
	DT_UDECIMAL                DType = 114
	DT_UDOUBLE                 DType = 115
	DT_UNION                   DType = 116
	DT_UNKNOWN                 DType = 117
	DT_USERDEFINED             DType = 118
	DT_USMALLINT               DType = 119
	DT_UTINYINT                DType = 120
	DT_UUID                    DType = 121
	DT_VARBINARY               DType = 122
	DT_VARCHAR                 DType = 123
	DT_VARIANT                 DType = 124
	DT_VECTOR                  DType = 125
	DT_XML                     DType = 126
	DT_YEAR                    DType = 127
	DT_TDIGEST                 DType = 128
)

const numDTypes = 129

var dtypeNames = [numDTypes]string{
	DT_ARRAY:                   "ARRAY",
	DT_AGGREGATEFUNCTION:       "AGGREGATEFUNCTION",
	DT_SIMPLEAGGREGATEFUNCTION: "SIMPLEAGGREGATEFUNCTION",
	DT_BIGDECIMAL:              "BIGDECIMAL",
	DT_BIGINT:                  "BIGINT",
	DT_BIGNUM:                  "BIGNUM",
	DT_BIGSERIAL:               "BIGSERIAL",
	DT_BINARY:                  "BINARY",
	DT_BIT:                     "BIT",
	DT_BLOB:                    "BLOB",
	DT_BOOLEAN:                 "BOOLEAN",
	DT_BPCHAR:                  "BPCHAR",
	DT_CHAR:                    "CHAR",
	DT_CHARACTER_SET:           "CHARACTER_SET",
	DT_DATE:                    "DATE",
	DT_DATE32:                  "DATE32",
	DT_DATEMULTIRANGE:          "DATEMULTIRANGE",
	DT_DATERANGE:               "DATERANGE",
	DT_DATETIME:                "DATETIME",
	DT_DATETIME2:               "DATETIME2",
	DT_DATETIME64:              "DATETIME64",
	DT_DECIMAL:                 "DECIMAL",
	DT_DECIMAL32:               "DECIMAL32",
	DT_DECIMAL64:               "DECIMAL64",
	DT_DECIMAL128:              "DECIMAL128",
	DT_DECIMAL256:              "DECIMAL256",
	DT_DECFLOAT:                "DECFLOAT",
	DT_DOUBLE:                  "DOUBLE",
	DT_DYNAMIC:                 "DYNAMIC",
	DT_ENUM:                    "ENUM",
	DT_ENUM8:                   "ENUM8",
	DT_ENUM16:                  "ENUM16",
	DT_FILE:                    "FILE",
	DT_FIXEDSTRING:             "FIXEDSTRING",
	DT_FLOAT:                   "FLOAT",
	DT_GEOGRAPHY:               "GEOGRAPHY",
	DT_GEOGRAPHYPOINT:          "GEOGRAPHYPOINT",
	DT_GEOMETRY:                "GEOMETRY",
	DT_POINT:                   "POINT",
	DT_RING:                    "RING",
	DT_LINESTRING:              "LINESTRING",
	DT_MULTILINESTRING:         "MULTILINESTRING",
	DT_POLYGON:                 "POLYGON",
	DT_MULTIPOLYGON:            "MULTIPOLYGON",
	DT_HLLSKETCH:               "HLLSKETCH",
	DT_HSTORE:                  "HSTORE",
	DT_IMAGE:                   "IMAGE",
	DT_INET:                    "INET",
	DT_INT:                     "INT",
	DT_INT128:                  "INT128",
	DT_INT256:                  "INT256",
	DT_INT4MULTIRANGE:          "INT4MULTIRANGE",
	DT_INT4RANGE:               "INT4RANGE",
	DT_INT8MULTIRANGE:          "INT8MULTIRANGE",
	DT_INT8RANGE:               "INT8RANGE",
	DT_INTERVAL:                "INTERVAL",
	DT_IPADDRESS:               "IPADDRESS",
	DT_IPPREFIX:                "IPPREFIX",
	DT_IPV4:                    "IPV4",
	DT_IPV6:                    "IPV6",
	DT_JSON:                    "JSON",
	DT_JSONB:                   "JSONB",
	DT_LIST:                    "LIST",
	DT_LONGBLOB:                "LONGBLOB",
	DT_LONGTEXT:                "LONGTEXT",
	DT_LOWCARDINALITY:          "LOWCARDINALITY",
	DT_MAP:                     "MAP",
	DT_MEDIUMBLOB:              "MEDIUMBLOB",
	DT_MEDIUMINT:               "MEDIUMINT",
	DT_MEDIUMTEXT:              "MEDIUMTEXT",
	DT_MONEY:                   "MONEY",
	DT_NAME:                    "NAME",
	DT_NCHAR:                   "NCHAR",
	DT_NESTED:                  "NESTED",
	DT_NOTHING:                 "NOTHING",
	DT_NULL:                    "NULL",
	DT_NUMMULTIRANGE:           "NUMMULTIRANGE",
	DT_NUMRANGE:                "NUMRANGE",
	DT_NVARCHAR:                "NVARCHAR",
	DT_OBJECT:                  "OBJECT",
	DT_RANGE:                   "RANGE",
	DT_ROWVERSION:              "ROWVERSION",
	DT_SERIAL:                  "SERIAL",
	DT_SET:                     "SET",
	DT_SMALLDATETIME:           "SMALLDATETIME",
	DT_SMALLINT:                "SMALLINT",
	DT_SMALLMONEY:              "SMALLMONEY",
	DT_SMALLSERIAL:             "SMALLSERIAL",
	DT_STRUCT:                  "STRUCT",
	DT_SUPER:                   "SUPER",
	DT_TEXT:                    "TEXT",
	DT_TINYBLOB:                "TINYBLOB",
	DT_TINYTEXT:                "TINYTEXT",
	DT_TIME:                    "TIME",
	DT_TIMETZ:                  "TIMETZ",
	DT_TIME_NS:                 "TIME_NS",
	DT_TIMESTAMP:               "TIMESTAMP",
	DT_TIMESTAMPNTZ:            "TIMESTAMPNTZ",
	DT_TIMESTAMPLTZ:            "TIMESTAMPLTZ",
	DT_TIMESTAMPTZ:             "TIMESTAMPTZ",
	DT_TIMESTAMP_S:             "TIMESTAMP_S",
	DT_TIMESTAMP_MS:            "TIMESTAMP_MS",
	DT_TIMESTAMP_NS:            "TIMESTAMP_NS",
	DT_TINYINT:                 "TINYINT",
	DT_TSMULTIRANGE:            "TSMULTIRANGE",
	DT_TSRANGE:                 "TSRANGE",
	DT_TSTZMULTIRANGE:          "TSTZMULTIRANGE",
	DT_TSTZRANGE:               "TSTZRANGE",
	DT_UBIGINT:                 "UBIGINT",
	DT_UINT:                    "UINT",
	DT_UINT128:                 "UINT128",
	DT_UINT256:                 "UINT256",
	DT_UMEDIUMINT:              "UMEDIUMINT",
	DT_UDECIMAL:                "UDECIMAL",
	DT_UDOUBLE:                 "UDOUBLE",
	DT_UNION:                   "UNION",
	DT_UNKNOWN:                 "UNKNOWN",
	DT_USERDEFINED:             "USERDEFINED",
	DT_USMALLINT:               "USMALLINT",
	DT_UTINYINT:                "UTINYINT",
	DT_UUID:                    "UUID",
	DT_VARBINARY:               "VARBINARY",
	DT_VARCHAR:                 "VARCHAR",
	DT_VARIANT:                 "VARIANT",
	DT_VECTOR:                  "VECTOR",
	DT_XML:                     "XML",
	DT_YEAR:                    "YEAR",
	DT_TDIGEST:                 "TDIGEST",
}

var dtypeValues = [numDTypes]string{
	DT_ARRAY:                   "ARRAY",
	DT_AGGREGATEFUNCTION:       "AGGREGATEFUNCTION",
	DT_SIMPLEAGGREGATEFUNCTION: "SIMPLEAGGREGATEFUNCTION",
	DT_BIGDECIMAL:              "BIGDECIMAL",
	DT_BIGINT:                  "BIGINT",
	DT_BIGNUM:                  "BIGNUM",
	DT_BIGSERIAL:               "BIGSERIAL",
	DT_BINARY:                  "BINARY",
	DT_BIT:                     "BIT",
	DT_BLOB:                    "BLOB",
	DT_BOOLEAN:                 "BOOLEAN",
	DT_BPCHAR:                  "BPCHAR",
	DT_CHAR:                    "CHAR",
	DT_CHARACTER_SET:           "CHARACTER_SET",
	DT_DATE:                    "DATE",
	DT_DATE32:                  "DATE32",
	DT_DATEMULTIRANGE:          "DATEMULTIRANGE",
	DT_DATERANGE:               "DATERANGE",
	DT_DATETIME:                "DATETIME",
	DT_DATETIME2:               "DATETIME2",
	DT_DATETIME64:              "DATETIME64",
	DT_DECIMAL:                 "DECIMAL",
	DT_DECIMAL32:               "DECIMAL32",
	DT_DECIMAL64:               "DECIMAL64",
	DT_DECIMAL128:              "DECIMAL128",
	DT_DECIMAL256:              "DECIMAL256",
	DT_DECFLOAT:                "DECFLOAT",
	DT_DOUBLE:                  "DOUBLE",
	DT_DYNAMIC:                 "DYNAMIC",
	DT_ENUM:                    "ENUM",
	DT_ENUM8:                   "ENUM8",
	DT_ENUM16:                  "ENUM16",
	DT_FILE:                    "FILE",
	DT_FIXEDSTRING:             "FIXEDSTRING",
	DT_FLOAT:                   "FLOAT",
	DT_GEOGRAPHY:               "GEOGRAPHY",
	DT_GEOGRAPHYPOINT:          "GEOGRAPHYPOINT",
	DT_GEOMETRY:                "GEOMETRY",
	DT_POINT:                   "POINT",
	DT_RING:                    "RING",
	DT_LINESTRING:              "LINESTRING",
	DT_MULTILINESTRING:         "MULTILINESTRING",
	DT_POLYGON:                 "POLYGON",
	DT_MULTIPOLYGON:            "MULTIPOLYGON",
	DT_HLLSKETCH:               "HLLSKETCH",
	DT_HSTORE:                  "HSTORE",
	DT_IMAGE:                   "IMAGE",
	DT_INET:                    "INET",
	DT_INT:                     "INT",
	DT_INT128:                  "INT128",
	DT_INT256:                  "INT256",
	DT_INT4MULTIRANGE:          "INT4MULTIRANGE",
	DT_INT4RANGE:               "INT4RANGE",
	DT_INT8MULTIRANGE:          "INT8MULTIRANGE",
	DT_INT8RANGE:               "INT8RANGE",
	DT_INTERVAL:                "INTERVAL",
	DT_IPADDRESS:               "IPADDRESS",
	DT_IPPREFIX:                "IPPREFIX",
	DT_IPV4:                    "IPV4",
	DT_IPV6:                    "IPV6",
	DT_JSON:                    "JSON",
	DT_JSONB:                   "JSONB",
	DT_LIST:                    "LIST",
	DT_LONGBLOB:                "LONGBLOB",
	DT_LONGTEXT:                "LONGTEXT",
	DT_LOWCARDINALITY:          "LOWCARDINALITY",
	DT_MAP:                     "MAP",
	DT_MEDIUMBLOB:              "MEDIUMBLOB",
	DT_MEDIUMINT:               "MEDIUMINT",
	DT_MEDIUMTEXT:              "MEDIUMTEXT",
	DT_MONEY:                   "MONEY",
	DT_NAME:                    "NAME",
	DT_NCHAR:                   "NCHAR",
	DT_NESTED:                  "NESTED",
	DT_NOTHING:                 "NOTHING",
	DT_NULL:                    "NULL",
	DT_NUMMULTIRANGE:           "NUMMULTIRANGE",
	DT_NUMRANGE:                "NUMRANGE",
	DT_NVARCHAR:                "NVARCHAR",
	DT_OBJECT:                  "OBJECT",
	DT_RANGE:                   "RANGE",
	DT_ROWVERSION:              "ROWVERSION",
	DT_SERIAL:                  "SERIAL",
	DT_SET:                     "SET",
	DT_SMALLDATETIME:           "SMALLDATETIME",
	DT_SMALLINT:                "SMALLINT",
	DT_SMALLMONEY:              "SMALLMONEY",
	DT_SMALLSERIAL:             "SMALLSERIAL",
	DT_STRUCT:                  "STRUCT",
	DT_SUPER:                   "SUPER",
	DT_TEXT:                    "TEXT",
	DT_TINYBLOB:                "TINYBLOB",
	DT_TINYTEXT:                "TINYTEXT",
	DT_TIME:                    "TIME",
	DT_TIMETZ:                  "TIMETZ",
	DT_TIME_NS:                 "TIME_NS",
	DT_TIMESTAMP:               "TIMESTAMP",
	DT_TIMESTAMPNTZ:            "TIMESTAMPNTZ",
	DT_TIMESTAMPLTZ:            "TIMESTAMPLTZ",
	DT_TIMESTAMPTZ:             "TIMESTAMPTZ",
	DT_TIMESTAMP_S:             "TIMESTAMP_S",
	DT_TIMESTAMP_MS:            "TIMESTAMP_MS",
	DT_TIMESTAMP_NS:            "TIMESTAMP_NS",
	DT_TINYINT:                 "TINYINT",
	DT_TSMULTIRANGE:            "TSMULTIRANGE",
	DT_TSRANGE:                 "TSRANGE",
	DT_TSTZMULTIRANGE:          "TSTZMULTIRANGE",
	DT_TSTZRANGE:               "TSTZRANGE",
	DT_UBIGINT:                 "UBIGINT",
	DT_UINT:                    "UINT",
	DT_UINT128:                 "UINT128",
	DT_UINT256:                 "UINT256",
	DT_UMEDIUMINT:              "UMEDIUMINT",
	DT_UDECIMAL:                "UDECIMAL",
	DT_UDOUBLE:                 "UDOUBLE",
	DT_UNION:                   "UNION",
	DT_UNKNOWN:                 "UNKNOWN",
	DT_USERDEFINED:             "USER-DEFINED",
	DT_USMALLINT:               "USMALLINT",
	DT_UTINYINT:                "UTINYINT",
	DT_UUID:                    "UUID",
	DT_VARBINARY:               "VARBINARY",
	DT_VARCHAR:                 "VARCHAR",
	DT_VARIANT:                 "VARIANT",
	DT_VECTOR:                  "VECTOR",
	DT_XML:                     "XML",
	DT_YEAR:                    "YEAR",
	DT_TDIGEST:                 "TDIGEST",
}

var (
	DataType_ARRAY_TYPES            = newDTypeSet(DT_ARRAY, DT_LIST)
	DataType_FLOAT_TYPES            = newDTypeSet(DT_DOUBLE, DT_FLOAT)
	DataType_INTEGER_TYPES          = newDTypeSet(DT_BIGINT, DT_BIT, DT_INT, DT_INT128, DT_INT256, DT_MEDIUMINT, DT_SMALLINT, DT_TINYINT, DT_UBIGINT, DT_UINT, DT_UINT128, DT_UINT256, DT_UMEDIUMINT, DT_USMALLINT, DT_UTINYINT)
	DataType_NESTED_TYPES           = newDTypeSet(DT_ARRAY, DT_FILE, DT_LIST, DT_MAP, DT_NESTED, DT_OBJECT, DT_STRUCT, DT_UNION)
	DataType_NUMERIC_TYPES          = newDTypeSet(DT_BIGDECIMAL, DT_BIGINT, DT_BIT, DT_DECFLOAT, DT_DECIMAL, DT_DECIMAL128, DT_DECIMAL256, DT_DECIMAL32, DT_DECIMAL64, DT_DOUBLE, DT_FLOAT, DT_INT, DT_INT128, DT_INT256, DT_MEDIUMINT, DT_MONEY, DT_SMALLINT, DT_SMALLMONEY, DT_TINYINT, DT_UBIGINT, DT_UDECIMAL, DT_UDOUBLE, DT_UINT, DT_UINT128, DT_UINT256, DT_UMEDIUMINT, DT_USMALLINT, DT_UTINYINT)
	DataType_REAL_TYPES             = newDTypeSet(DT_BIGDECIMAL, DT_DECFLOAT, DT_DECIMAL, DT_DECIMAL128, DT_DECIMAL256, DT_DECIMAL32, DT_DECIMAL64, DT_DOUBLE, DT_FLOAT, DT_MONEY, DT_SMALLMONEY, DT_UDECIMAL, DT_UDOUBLE)
	DataType_SIGNED_INTEGER_TYPES   = newDTypeSet(DT_BIGINT, DT_INT, DT_INT128, DT_INT256, DT_MEDIUMINT, DT_SMALLINT, DT_TINYINT)
	DataType_STRUCT_TYPES           = newDTypeSet(DT_FILE, DT_NESTED, DT_OBJECT, DT_STRUCT, DT_UNION)
	DataType_TEMPORAL_TYPES         = newDTypeSet(DT_DATE, DT_DATE32, DT_DATETIME, DT_DATETIME2, DT_DATETIME64, DT_SMALLDATETIME, DT_TIME, DT_TIMESTAMP, DT_TIMESTAMPLTZ, DT_TIMESTAMPNTZ, DT_TIMESTAMPTZ, DT_TIMESTAMP_MS, DT_TIMESTAMP_NS, DT_TIMESTAMP_S, DT_TIMETZ)
	DataType_TEXT_TYPES             = newDTypeSet(DT_CHAR, DT_NAME, DT_NCHAR, DT_NVARCHAR, DT_TEXT, DT_VARCHAR)
	DataType_UNSIGNED_INTEGER_TYPES = newDTypeSet(DT_UBIGINT, DT_UINT, DT_UINT128, DT_UINT256, DT_UMEDIUMINT, DT_USMALLINT, DT_UTINYINT)
)
