// Code generated by pkg/sqlengine/codegen/gen.py from sqlglot 30.13.0. DO NOT EDIT.

package sqlengine

// TokenType mirrors sqlglot.tokens.TokenType.
type TokenType uint16

const (
	TK_NONE                    TokenType = 0
	TK_L_PAREN                 TokenType = 1
	TK_R_PAREN                 TokenType = 2
	TK_L_BRACKET               TokenType = 3
	TK_R_BRACKET               TokenType = 4
	TK_L_BRACE                 TokenType = 5
	TK_R_BRACE                 TokenType = 6
	TK_COMMA                   TokenType = 7
	TK_DOT                     TokenType = 8
	TK_DASH                    TokenType = 9
	TK_PLUS                    TokenType = 10
	TK_COLON                   TokenType = 11
	TK_DOTCOLON                TokenType = 12
	TK_DOTCARET                TokenType = 13
	TK_DCOLON                  TokenType = 14
	TK_DCOLONDOLLAR            TokenType = 15
	TK_DCOLONPERCENT           TokenType = 16
	TK_DCOLONQMARK             TokenType = 17
	TK_DQMARK                  TokenType = 18
	TK_SEMICOLON               TokenType = 19
	TK_STAR                    TokenType = 20
	TK_BACKSLASH               TokenType = 21
	TK_SLASH                   TokenType = 22
	TK_LT                      TokenType = 23
	TK_LTE                     TokenType = 24
	TK_GT                      TokenType = 25
	TK_GTE                     TokenType = 26
	TK_NOT                     TokenType = 27
	TK_EQ                      TokenType = 28
	TK_NEQ                     TokenType = 29
	TK_NULLSAFE_EQ             TokenType = 30
	TK_COLON_EQ                TokenType = 31
	TK_COLON_GT                TokenType = 32
	TK_NCOLON_GT               TokenType = 33
	TK_AND                     TokenType = 34
	TK_OR                      TokenType = 35
	TK_AMP                     TokenType = 36
	TK_DPIPE                   TokenType = 37
	TK_PIPE_GT                 TokenType = 38
	TK_PIPE                    TokenType = 39
	TK_PIPE_SLASH              TokenType = 40
	TK_DPIPE_SLASH             TokenType = 41
	TK_CARET                   TokenType = 42
	TK_CARET_AT                TokenType = 43
	TK_TILDE                   TokenType = 44
	TK_ARROW                   TokenType = 45
	TK_DARROW                  TokenType = 46
	TK_FARROW                  TokenType = 47
	TK_HASH                    TokenType = 48
	TK_HASH_ARROW              TokenType = 49
	TK_DHASH_ARROW             TokenType = 50
	TK_LR_ARROW                TokenType = 51
	TK_LLRR_ARROW              TokenType = 52
	TK_DAT                     TokenType = 53
	TK_AT_QMARK                TokenType = 54
	TK_LT_AT                   TokenType = 55
	TK_AT_GT                   TokenType = 56
	TK_DOLLAR                  TokenType = 57
	TK_PARAMETER               TokenType = 58
	TK_SESSION                 TokenType = 59
	TK_SESSION_PARAMETER       TokenType = 60
	TK_SESSION_USER            TokenType = 61
	TK_DAMP                    TokenType = 62
	TK_AMP_LT                  TokenType = 63
	TK_AMP_GT                  TokenType = 64
	TK_ADJACENT                TokenType = 65
	TK_XOR                     TokenType = 66
	TK_DSTAR                   TokenType = 67
	TK_QMARK_AMP               TokenType = 68
	TK_QMARK_PIPE              TokenType = 69
	TK_HASH_DASH               TokenType = 70
	TK_EXCLAMATION             TokenType = 71
	TK_URI_START               TokenType = 72
	TK_BLOCK_START             TokenType = 73
	TK_BLOCK_END               TokenType = 74
	TK_SPACE                   TokenType = 75
	TK_BREAK                   TokenType = 76
	TK_STRING                  TokenType = 77
	TK_NUMBER                  TokenType = 78
	TK_IDENTIFIER              TokenType = 79
	TK_DATABASE                TokenType = 80
	TK_COLUMN                  TokenType = 81
	TK_COLUMN_DEF              TokenType = 82
	TK_SCHEMA                  TokenType = 83
	TK_TABLE                   TokenType = 84
	TK_WAREHOUSE               TokenType = 85
	TK_STAGE                   TokenType = 86
	TK_STREAM                  TokenType = 87
	TK_STREAMLIT               TokenType = 88
	TK_VAR                     TokenType = 89
	TK_BIT_STRING              TokenType = 90
	TK_HEX_STRING              TokenType = 91
	TK_BYTE_STRING             TokenType = 92
	TK_NATIONAL_STRING         TokenType = 93
	TK_RAW_STRING              TokenType = 94
	TK_HEREDOC_STRING          TokenType = 95
	TK_UNICODE_STRING          TokenType = 96
	TK_BIT                     TokenType = 97
	TK_BOOLEAN                 TokenType = 98
	TK_TINYINT                 TokenType = 99
	TK_UTINYINT                TokenType = 100
	TK_SMALLINT                TokenType = 101
	TK_USMALLINT               TokenType = 102
	TK_MEDIUMINT               TokenType = 103
	TK_UMEDIUMINT              TokenType = 104
	TK_INT                     TokenType = 105
	TK_UINT                    TokenType = 106
	TK_BIGINT                  TokenType = 107
	TK_UBIGINT                 TokenType = 108
	TK_BIGNUM                  TokenType = 109
	TK_INT128                  TokenType = 110
	TK_UINT128                 TokenType = 111
	TK_INT256                  TokenType = 112
	TK_UINT256                 TokenType = 113
	TK_FLOAT                   TokenType = 114
	TK_DOUBLE                  TokenType = 115
	TK_UDOUBLE                 TokenType = 116
	TK_DECIMAL                 TokenType = 117
	TK_DECIMAL32               TokenType = 118
	TK_DECIMAL64               TokenType = 119
	TK_DECIMAL128              TokenType = 120
	TK_DECIMAL256              TokenType = 121
	TK_DECFLOAT                TokenType = 122
	TK_UDECIMAL                TokenType = 123
	TK_BIGDECIMAL              TokenType = 124
	TK_CHAR                    TokenType = 125
	TK_NCHAR                   TokenType = 126
	TK_VARCHAR                 TokenType = 127
	TK_NVARCHAR                TokenType = 128
	TK_BPCHAR                  TokenType = 129
	TK_TEXT                    TokenType = 130
	TK_MEDIUMTEXT              TokenType = 131
	TK_LONGTEXT                TokenType = 132
	TK_BLOB                    TokenType = 133
	TK_MEDIUMBLOB              TokenType = 134
	TK_LONGBLOB                TokenType = 135
	TK_TINYBLOB                TokenType = 136
	TK_TINYTEXT                TokenType = 137
	TK_NAME                    TokenType = 138
	TK_BINARY                  TokenType = 139
	TK_VARBINARY               TokenType = 140
	TK_JSON                    TokenType = 141
	TK_JSONB                   TokenType = 142
	TK_TIME                    TokenType = 143
	TK_TIMETZ                  TokenType = 144
	TK_TIME_NS                 TokenType = 145
	TK_TIMESTAMP               TokenType = 146
	TK_TIMESTAMPTZ             TokenType = 147
	TK_TIMESTAMPLTZ            TokenType = 148
	TK_TIMESTAMPNTZ            TokenType = 149
	TK_TIMESTAMP_S             TokenType = 150
	TK_TIMESTAMP_MS            TokenType = 151
	TK_TIMESTAMP_NS            TokenType = 152
	TK_DATETIME                TokenType = 153
	TK_DATETIME2               TokenType = 154
	TK_DATETIME64              TokenType = 155
	TK_SMALLDATETIME           TokenType = 156
	TK_DATE                    TokenType = 157
	TK_DATE32                  TokenType = 158
	TK_INT4RANGE               TokenType = 159
	TK_INT4MULTIRANGE          TokenType = 160
	TK_INT8RANGE               TokenType = 161
	TK_INT8MULTIRANGE          TokenType = 162
	TK_NUMRANGE                TokenType = 163
	TK_NUMMULTIRANGE           TokenType = 164
	TK_TSRANGE                 TokenType = 165
	TK_TSMULTIRANGE            TokenType = 166
	TK_TSTZRANGE               TokenType = 167
	TK_TSTZMULTIRANGE          TokenType = 168
	TK_DATERANGE               TokenType = 169
	TK_DATEMULTIRANGE          TokenType = 170
	TK_UUID                    TokenType = 171
	TK_GEOGRAPHY               TokenType = 172
	TK_GEOGRAPHYPOINT          TokenType = 173
	TK_NULLABLE                TokenType = 174
	TK_GEOMETRY                TokenType = 175
	TK_POINT                   TokenType = 176
	TK_RING                    TokenType = 177
	TK_LINESTRING              TokenType = 178
	TK_LOCALTIME               TokenType = 179
	TK_LOCALTIMESTAMP          TokenType = 180
	TK_SYSTIMESTAMP            TokenType = 181
	TK_MULTILINESTRING         TokenType = 182
	TK_POLYGON                 TokenType = 183
	TK_MULTIPOLYGON            TokenType = 184
	TK_HLLSKETCH               TokenType = 185
	TK_HSTORE                  TokenType = 186
	TK_SUPER                   TokenType = 187
	TK_SERIAL                  TokenType = 188
	TK_SMALLSERIAL             TokenType = 189
	TK_BIGSERIAL               TokenType = 190
	TK_XML                     TokenType = 191
	TK_YEAR                    TokenType = 192
	TK_USERDEFINED             TokenType = 193
	TK_MONEY                   TokenType = 194
	TK_SMALLMONEY              TokenType = 195
	TK_ROWVERSION              TokenType = 196
	TK_IMAGE                   TokenType = 197
	TK_VARIANT                 TokenType = 198
	TK_OBJECT                  TokenType = 199
	TK_INET                    TokenType = 200
	TK_IPADDRESS               TokenType = 201
	TK_IPPREFIX                TokenType = 202
	TK_IPV4                    TokenType = 203
	TK_IPV6                    TokenType = 204
	TK_ENUM                    TokenType = 205
	TK_ENUM8                   TokenType = 206
	TK_ENUM16                  TokenType = 207
	TK_FIXEDSTRING             TokenType = 208
	TK_LOWCARDINALITY          TokenType = 209
	TK_NESTED                  TokenType = 210
	TK_AGGREGATEFUNCTION       TokenType = 211
	TK_SIMPLEAGGREGATEFUNCTION TokenType = 212
	TK_TDIGEST                 TokenType = 213
	TK_UNKNOWN                 TokenType = 214
	TK_VECTOR                  TokenType = 215
	TK_DYNAMIC                 TokenType = 216
	TK_VOID                    TokenType = 217
	TK_ALIAS                   TokenType = 218
	TK_ALTER                   TokenType = 219
	TK_ALL                     TokenType = 220
	TK_ANTI                    TokenType = 221
	TK_ANY                     TokenType = 222
	TK_APPLY                   TokenType = 223
	TK_ARRAY                   TokenType = 224
	TK_ASC                     TokenType = 225
	TK_ASOF                    TokenType = 226
	TK_ATTACH                  TokenType = 227
	TK_AUTO_INCREMENT          TokenType = 228
	TK_BEGIN                   TokenType = 229
	TK_BETWEEN                 TokenType = 230
	TK_BULK_COLLECT_INTO       TokenType = 231
	TK_CACHE                   TokenType = 232
	TK_CASE                    TokenType = 233
	TK_CHARACTER_SET           TokenType = 234
	TK_CLUSTER_BY              TokenType = 235
	TK_COLLATE                 TokenType = 236
	TK_COMMAND                 TokenType = 237
	TK_COMMENT                 TokenType = 238
	TK_COMMIT                  TokenType = 239
	TK_CONNECT_BY              TokenType = 240
	TK_CONSTRAINT              TokenType = 241
	TK_COPY                    TokenType = 242
	TK_CREATE                  TokenType = 243
	TK_CROSS                   TokenType = 244
	TK_CUBE                    TokenType = 245
	TK_CURRENT_DATE            TokenType = 246
	TK_CURRENT_DATETIME        TokenType = 247
	TK_CURRENT_SCHEMA          TokenType = 248
	TK_CURRENT_TIME            TokenType = 249
	TK_CURRENT_TIMESTAMP       TokenType = 250
	TK_CURRENT_USER            TokenType = 251
	TK_CURRENT_USER_ID         TokenType = 252
	TK_CURRENT_ROLE            TokenType = 253
	TK_CURRENT_CATALOG         TokenType = 254
	TK_DECLARE                 TokenType = 255
	TK_DEFAULT                 TokenType = 256
	TK_DELETE                  TokenType = 257
	TK_DESC                    TokenType = 258
	TK_DESCRIBE                TokenType = 259
	TK_DETACH                  TokenType = 260
	TK_DICTIONARY              TokenType = 261
	TK_DISTINCT                TokenType = 262
	TK_DISTRIBUTE_BY           TokenType = 263
	TK_DIV                     TokenType = 264
	TK_DROP                    TokenType = 265
	TK_ELSE                    TokenType = 266
	TK_END                     TokenType = 267
	TK_ESCAPE                  TokenType = 268
	TK_EXCEPT                  TokenType = 269
	TK_EXECUTE                 TokenType = 270
	TK_EXISTS                  TokenType = 271
	TK_FALSE                   TokenType = 272
	TK_FETCH                   TokenType = 273
	TK_FILE                    TokenType = 274
	TK_FILE_FORMAT             TokenType = 275
	TK_FILTER                  TokenType = 276
	TK_FINAL                   TokenType = 277
	TK_FIRST                   TokenType = 278
	TK_FOR                     TokenType = 279
	TK_FORCE                   TokenType = 280
	TK_FOREIGN_KEY             TokenType = 281
	TK_FORMAT                  TokenType = 282
	TK_FROM                    TokenType = 283
	TK_FULL                    TokenType = 284
	TK_FUNCTION                TokenType = 285
	TK_GET                     TokenType = 286
	TK_GLOB                    TokenType = 287
	TK_GLOBAL                  TokenType = 288
	TK_GRANT                   TokenType = 289
	TK_GROUP_BY                TokenType = 290
	TK_GROUPING_SETS           TokenType = 291
	TK_HAVING                  TokenType = 292
	TK_HINT                    TokenType = 293
	TK_IGNORE                  TokenType = 294
	TK_ILIKE                   TokenType = 295
	TK_IN                      TokenType = 296
	TK_INDEX                   TokenType = 297
	TK_INDEXED_BY              TokenType = 298
	TK_INNER                   TokenType = 299
	TK_INSERT                  TokenType = 300
	TK_INSTALL                 TokenType = 301
	TK_INTEGRATION             TokenType = 302
	TK_INTERSECT               TokenType = 303
	TK_INTERVAL                TokenType = 304
	TK_INTO                    TokenType = 305
	TK_INTRODUCER              TokenType = 306
	TK_IRLIKE                  TokenType = 307
	TK_IS                      TokenType = 308
	TK_ISNULL                  TokenType = 309
	TK_JOIN                    TokenType = 310
	TK_JOIN_MARKER             TokenType = 311
	TK_KEEP                    TokenType = 312
	TK_KEY                     TokenType = 313
	TK_KILL                    TokenType = 314
	TK_LANGUAGE                TokenType = 315
	TK_LATERAL                 TokenType = 316
	TK_LEFT                    TokenType = 317
	TK_LIKE                    TokenType = 318
	TK_LIMIT                   TokenType = 319
	TK_LIST                    TokenType = 320
	TK_LOAD                    TokenType = 321
	TK_LOCK                    TokenType = 322
	TK_MAP                     TokenType = 323
	TK_MATCH                   TokenType = 324
	TK_MATCH_CONDITION         TokenType = 325
	TK_MATCH_RECOGNIZE         TokenType = 326
	TK_MEMBER_OF               TokenType = 327
	TK_MERGE                   TokenType = 328
	TK_MOD                     TokenType = 329
	TK_MODEL                   TokenType = 330
	TK_NATURAL                 TokenType = 331
	TK_NEXT                    TokenType = 332
	TK_NOTHING                 TokenType = 333
	TK_NOTNULL                 TokenType = 334
	TK_NULL                    TokenType = 335
	TK_OBJECT_IDENTIFIER       TokenType = 336
	TK_OFFSET                  TokenType = 337
	TK_ON                      TokenType = 338
	TK_ONLY                    TokenType = 339
	TK_OPERATOR                TokenType = 340
	TK_ORDER_BY                TokenType = 341
	TK_ORDER_SIBLINGS_BY       TokenType = 342
	TK_ORDERED                 TokenType = 343
	TK_ORDINALITY              TokenType = 344
	TK_OUT                     TokenType = 345
	TK_INOUT                   TokenType = 346
	TK_OUTER                   TokenType = 347
	TK_OVER                    TokenType = 348
	TK_OVERLAPS                TokenType = 349
	TK_OVERWRITE               TokenType = 350
	TK_PACKAGE                 TokenType = 351
	TK_PARTITION               TokenType = 352
	TK_PARTITION_BY            TokenType = 353
	TK_PERCENT                 TokenType = 354
	TK_PIVOT                   TokenType = 355
	TK_PLACEHOLDER             TokenType = 356
	TK_POLICY                  TokenType = 357
	TK_POOL                    TokenType = 358
	TK_POSITIONAL              TokenType = 359
	TK_PRAGMA                  TokenType = 360
	TK_PREWHERE                TokenType = 361
	TK_PRIMARY_KEY             TokenType = 362
	TK_PROCEDURE               TokenType = 363
	TK_PROPERTIES              TokenType = 364
	TK_PROJECTION              TokenType = 365
	TK_PSEUDO_TYPE             TokenType = 366
	TK_PUT                     TokenType = 367
	TK_QUALIFY                 TokenType = 368
	TK_QUOTE                   TokenType = 369
	TK_QDCOLON                 TokenType = 370
	TK_RANGE                   TokenType = 371
	TK_RECURSIVE               TokenType = 372
	TK_REFRESH                 TokenType = 373
	TK_RENAME                  TokenType = 374
	TK_REPLACE                 TokenType = 375
	TK_RETURNING               TokenType = 376
	TK_REVOKE                  TokenType = 377
	TK_REFERENCES              TokenType = 378
	TK_RIGHT                   TokenType = 379
	TK_RLIKE                   TokenType = 380
	TK_ROLE                    TokenType = 381
	TK_ROLLBACK                TokenType = 382
	TK_ROLLUP                  TokenType = 383
	TK_ROW                     TokenType = 384
	TK_ROWS                    TokenType = 385
	TK_RULE                    TokenType = 386
	TK_SELECT                  TokenType = 387
	TK_SEMI                    TokenType = 388
	TK_SEPARATOR               TokenType = 389
	TK_SEQUENCE                TokenType = 390
	TK_SERDE_PROPERTIES        TokenType = 391
	TK_SET                     TokenType = 392
	TK_SETTINGS                TokenType = 393
	TK_SHOW                    TokenType = 394
	TK_SIMILAR_TO              TokenType = 395
	TK_SOME                    TokenType = 396
	TK_SORT_BY                 TokenType = 397
	TK_SOUNDS_LIKE             TokenType = 398
	TK_SQL_SECURITY            TokenType = 399
	TK_START_WITH              TokenType = 400
	TK_STORAGE_INTEGRATION     TokenType = 401
	TK_STRAIGHT_JOIN           TokenType = 402
	TK_STRUCT                  TokenType = 403
	TK_SUMMARIZE               TokenType = 404
	TK_TABLE_SAMPLE            TokenType = 405
	TK_TAG                     TokenType = 406
	TK_TEMPORARY               TokenType = 407
	TK_TOP                     TokenType = 408
	TK_THEN                    TokenType = 409
	TK_TRUE                    TokenType = 410
	TK_TRUNCATE                TokenType = 411
	TK_TRIGGER                 TokenType = 412
	TK_TYPE                    TokenType = 413
	TK_UNCACHE                 TokenType = 414
	TK_UNDROP                  TokenType = 415
	TK_UNION                   TokenType = 416
	TK_UNNEST                  TokenType = 417
	TK_UNPIVOT                 TokenType = 418
	TK_UPDATE                  TokenType = 419
	TK_USE                     TokenType = 420
	TK_USING                   TokenType = 421
	TK_VALUES                  TokenType = 422
	TK_VARIADIC                TokenType = 423
	TK_VIEW                    TokenType = 424
	TK_SEMANTIC_VIEW           TokenType = 425
	TK_VOLATILE                TokenType = 426
	TK_VOLUME                  TokenType = 427
	TK_WHEN                    TokenType = 428
	TK_WHERE                   TokenType = 429
	TK_WINDOW                  TokenType = 430
	TK_WITH                    TokenType = 431
	TK_UNIQUE                  TokenType = 432
	TK_UTC_DATE                TokenType = 433
	TK_UTC_TIME                TokenType = 434
	TK_UTC_TIMESTAMP           TokenType = 435
	TK_VERSION_SNAPSHOT        TokenType = 436
	TK_TIMESTAMP_SNAPSHOT      TokenType = 437
	TK_OPTION                  TokenType = 438
	TK_SINK                    TokenType = 439
	TK_SOURCE                  TokenType = 440
	TK_ANALYZE                 TokenType = 441
	TK_NAMESPACE               TokenType = 442
	TK_EXPORT                  TokenType = 443
	TK_HIVE_TOKEN_STREAM       TokenType = 444
	TK_SENTINEL                TokenType = 445
)

const numTokenTypes = 446

var tokenTypeNames = [numTokenTypes]string{
	TK_L_PAREN:                 "L_PAREN",
	TK_R_PAREN:                 "R_PAREN",
	TK_L_BRACKET:               "L_BRACKET",
	TK_R_BRACKET:               "R_BRACKET",
	TK_L_BRACE:                 "L_BRACE",
	TK_R_BRACE:                 "R_BRACE",
	TK_COMMA:                   "COMMA",
	TK_DOT:                     "DOT",
	TK_DASH:                    "DASH",
	TK_PLUS:                    "PLUS",
	TK_COLON:                   "COLON",
	TK_DOTCOLON:                "DOTCOLON",
	TK_DOTCARET:                "DOTCARET",
	TK_DCOLON:                  "DCOLON",
	TK_DCOLONDOLLAR:            "DCOLONDOLLAR",
	TK_DCOLONPERCENT:           "DCOLONPERCENT",
	TK_DCOLONQMARK:             "DCOLONQMARK",
	TK_DQMARK:                  "DQMARK",
	TK_SEMICOLON:               "SEMICOLON",
	TK_STAR:                    "STAR",
	TK_BACKSLASH:               "BACKSLASH",
	TK_SLASH:                   "SLASH",
	TK_LT:                      "LT",
	TK_LTE:                     "LTE",
	TK_GT:                      "GT",
	TK_GTE:                     "GTE",
	TK_NOT:                     "NOT",
	TK_EQ:                      "EQ",
	TK_NEQ:                     "NEQ",
	TK_NULLSAFE_EQ:             "NULLSAFE_EQ",
	TK_COLON_EQ:                "COLON_EQ",
	TK_COLON_GT:                "COLON_GT",
	TK_NCOLON_GT:               "NCOLON_GT",
	TK_AND:                     "AND",
	TK_OR:                      "OR",
	TK_AMP:                     "AMP",
	TK_DPIPE:                   "DPIPE",
	TK_PIPE_GT:                 "PIPE_GT",
	TK_PIPE:                    "PIPE",
	TK_PIPE_SLASH:              "PIPE_SLASH",
	TK_DPIPE_SLASH:             "DPIPE_SLASH",
	TK_CARET:                   "CARET",
	TK_CARET_AT:                "CARET_AT",
	TK_TILDE:                   "TILDE",
	TK_ARROW:                   "ARROW",
	TK_DARROW:                  "DARROW",
	TK_FARROW:                  "FARROW",
	TK_HASH:                    "HASH",
	TK_HASH_ARROW:              "HASH_ARROW",
	TK_DHASH_ARROW:             "DHASH_ARROW",
	TK_LR_ARROW:                "LR_ARROW",
	TK_LLRR_ARROW:              "LLRR_ARROW",
	TK_DAT:                     "DAT",
	TK_AT_QMARK:                "AT_QMARK",
	TK_LT_AT:                   "LT_AT",
	TK_AT_GT:                   "AT_GT",
	TK_DOLLAR:                  "DOLLAR",
	TK_PARAMETER:               "PARAMETER",
	TK_SESSION:                 "SESSION",
	TK_SESSION_PARAMETER:       "SESSION_PARAMETER",
	TK_SESSION_USER:            "SESSION_USER",
	TK_DAMP:                    "DAMP",
	TK_AMP_LT:                  "AMP_LT",
	TK_AMP_GT:                  "AMP_GT",
	TK_ADJACENT:                "ADJACENT",
	TK_XOR:                     "XOR",
	TK_DSTAR:                   "DSTAR",
	TK_QMARK_AMP:               "QMARK_AMP",
	TK_QMARK_PIPE:              "QMARK_PIPE",
	TK_HASH_DASH:               "HASH_DASH",
	TK_EXCLAMATION:             "EXCLAMATION",
	TK_URI_START:               "URI_START",
	TK_BLOCK_START:             "BLOCK_START",
	TK_BLOCK_END:               "BLOCK_END",
	TK_SPACE:                   "SPACE",
	TK_BREAK:                   "BREAK",
	TK_STRING:                  "STRING",
	TK_NUMBER:                  "NUMBER",
	TK_IDENTIFIER:              "IDENTIFIER",
	TK_DATABASE:                "DATABASE",
	TK_COLUMN:                  "COLUMN",
	TK_COLUMN_DEF:              "COLUMN_DEF",
	TK_SCHEMA:                  "SCHEMA",
	TK_TABLE:                   "TABLE",
	TK_WAREHOUSE:               "WAREHOUSE",
	TK_STAGE:                   "STAGE",
	TK_STREAM:                  "STREAM",
	TK_STREAMLIT:               "STREAMLIT",
	TK_VAR:                     "VAR",
	TK_BIT_STRING:              "BIT_STRING",
	TK_HEX_STRING:              "HEX_STRING",
	TK_BYTE_STRING:             "BYTE_STRING",
	TK_NATIONAL_STRING:         "NATIONAL_STRING",
	TK_RAW_STRING:              "RAW_STRING",
	TK_HEREDOC_STRING:          "HEREDOC_STRING",
	TK_UNICODE_STRING:          "UNICODE_STRING",
	TK_BIT:                     "BIT",
	TK_BOOLEAN:                 "BOOLEAN",
	TK_TINYINT:                 "TINYINT",
	TK_UTINYINT:                "UTINYINT",
	TK_SMALLINT:                "SMALLINT",
	TK_USMALLINT:               "USMALLINT",
	TK_MEDIUMINT:               "MEDIUMINT",
	TK_UMEDIUMINT:              "UMEDIUMINT",
	TK_INT:                     "INT",
	TK_UINT:                    "UINT",
	TK_BIGINT:                  "BIGINT",
	TK_UBIGINT:                 "UBIGINT",
	TK_BIGNUM:                  "BIGNUM",
	TK_INT128:                  "INT128",
	TK_UINT128:                 "UINT128",
	TK_INT256:                  "INT256",
	TK_UINT256:                 "UINT256",
	TK_FLOAT:                   "FLOAT",
	TK_DOUBLE:                  "DOUBLE",
	TK_UDOUBLE:                 "UDOUBLE",
	TK_DECIMAL:                 "DECIMAL",
	TK_DECIMAL32:               "DECIMAL32",
	TK_DECIMAL64:               "DECIMAL64",
	TK_DECIMAL128:              "DECIMAL128",
	TK_DECIMAL256:              "DECIMAL256",
	TK_DECFLOAT:                "DECFLOAT",
	TK_UDECIMAL:                "UDECIMAL",
	TK_BIGDECIMAL:              "BIGDECIMAL",
	TK_CHAR:                    "CHAR",
	TK_NCHAR:                   "NCHAR",
	TK_VARCHAR:                 "VARCHAR",
	TK_NVARCHAR:                "NVARCHAR",
	TK_BPCHAR:                  "BPCHAR",
	TK_TEXT:                    "TEXT",
	TK_MEDIUMTEXT:              "MEDIUMTEXT",
	TK_LONGTEXT:                "LONGTEXT",
	TK_BLOB:                    "BLOB",
	TK_MEDIUMBLOB:              "MEDIUMBLOB",
	TK_LONGBLOB:                "LONGBLOB",
	TK_TINYBLOB:                "TINYBLOB",
	TK_TINYTEXT:                "TINYTEXT",
	TK_NAME:                    "NAME",
	TK_BINARY:                  "BINARY",
	TK_VARBINARY:               "VARBINARY",
	TK_JSON:                    "JSON",
	TK_JSONB:                   "JSONB",
	TK_TIME:                    "TIME",
	TK_TIMETZ:                  "TIMETZ",
	TK_TIME_NS:                 "TIME_NS",
	TK_TIMESTAMP:               "TIMESTAMP",
	TK_TIMESTAMPTZ:             "TIMESTAMPTZ",
	TK_TIMESTAMPLTZ:            "TIMESTAMPLTZ",
	TK_TIMESTAMPNTZ:            "TIMESTAMPNTZ",
	TK_TIMESTAMP_S:             "TIMESTAMP_S",
	TK_TIMESTAMP_MS:            "TIMESTAMP_MS",
	TK_TIMESTAMP_NS:            "TIMESTAMP_NS",
	TK_DATETIME:                "DATETIME",
	TK_DATETIME2:               "DATETIME2",
	TK_DATETIME64:              "DATETIME64",
	TK_SMALLDATETIME:           "SMALLDATETIME",
	TK_DATE:                    "DATE",
	TK_DATE32:                  "DATE32",
	TK_INT4RANGE:               "INT4RANGE",
	TK_INT4MULTIRANGE:          "INT4MULTIRANGE",
	TK_INT8RANGE:               "INT8RANGE",
	TK_INT8MULTIRANGE:          "INT8MULTIRANGE",
	TK_NUMRANGE:                "NUMRANGE",
	TK_NUMMULTIRANGE:           "NUMMULTIRANGE",
	TK_TSRANGE:                 "TSRANGE",
	TK_TSMULTIRANGE:            "TSMULTIRANGE",
	TK_TSTZRANGE:               "TSTZRANGE",
	TK_TSTZMULTIRANGE:          "TSTZMULTIRANGE",
	TK_DATERANGE:               "DATERANGE",
	TK_DATEMULTIRANGE:          "DATEMULTIRANGE",
	TK_UUID:                    "UUID",
	TK_GEOGRAPHY:               "GEOGRAPHY",
	TK_GEOGRAPHYPOINT:          "GEOGRAPHYPOINT",
	TK_NULLABLE:                "NULLABLE",
	TK_GEOMETRY:                "GEOMETRY",
	TK_POINT:                   "POINT",
	TK_RING:                    "RING",
	TK_LINESTRING:              "LINESTRING",
	TK_LOCALTIME:               "LOCALTIME",
	TK_LOCALTIMESTAMP:          "LOCALTIMESTAMP",
	TK_SYSTIMESTAMP:            "SYSTIMESTAMP",
	TK_MULTILINESTRING:         "MULTILINESTRING",
	TK_POLYGON:                 "POLYGON",
	TK_MULTIPOLYGON:            "MULTIPOLYGON",
	TK_HLLSKETCH:               "HLLSKETCH",
	TK_HSTORE:                  "HSTORE",
	TK_SUPER:                   "SUPER",
	TK_SERIAL:                  "SERIAL",
	TK_SMALLSERIAL:             "SMALLSERIAL",
	TK_BIGSERIAL:               "BIGSERIAL",
	TK_XML:                     "XML",
	TK_YEAR:                    "YEAR",
	TK_USERDEFINED:             "USERDEFINED",
	TK_MONEY:                   "MONEY",
	TK_SMALLMONEY:              "SMALLMONEY",
	TK_ROWVERSION:              "ROWVERSION",
	TK_IMAGE:                   "IMAGE",
	TK_VARIANT:                 "VARIANT",
	TK_OBJECT:                  "OBJECT",
	TK_INET:                    "INET",
	TK_IPADDRESS:               "IPADDRESS",
	TK_IPPREFIX:                "IPPREFIX",
	TK_IPV4:                    "IPV4",
	TK_IPV6:                    "IPV6",
	TK_ENUM:                    "ENUM",
	TK_ENUM8:                   "ENUM8",
	TK_ENUM16:                  "ENUM16",
	TK_FIXEDSTRING:             "FIXEDSTRING",
	TK_LOWCARDINALITY:          "LOWCARDINALITY",
	TK_NESTED:                  "NESTED",
	TK_AGGREGATEFUNCTION:       "AGGREGATEFUNCTION",
	TK_SIMPLEAGGREGATEFUNCTION: "SIMPLEAGGREGATEFUNCTION",
	TK_TDIGEST:                 "TDIGEST",
	TK_UNKNOWN:                 "UNKNOWN",
	TK_VECTOR:                  "VECTOR",
	TK_DYNAMIC:                 "DYNAMIC",
	TK_VOID:                    "VOID",
	TK_ALIAS:                   "ALIAS",
	TK_ALTER:                   "ALTER",
	TK_ALL:                     "ALL",
	TK_ANTI:                    "ANTI",
	TK_ANY:                     "ANY",
	TK_APPLY:                   "APPLY",
	TK_ARRAY:                   "ARRAY",
	TK_ASC:                     "ASC",
	TK_ASOF:                    "ASOF",
	TK_ATTACH:                  "ATTACH",
	TK_AUTO_INCREMENT:          "AUTO_INCREMENT",
	TK_BEGIN:                   "BEGIN",
	TK_BETWEEN:                 "BETWEEN",
	TK_BULK_COLLECT_INTO:       "BULK_COLLECT_INTO",
	TK_CACHE:                   "CACHE",
	TK_CASE:                    "CASE",
	TK_CHARACTER_SET:           "CHARACTER_SET",
	TK_CLUSTER_BY:              "CLUSTER_BY",
	TK_COLLATE:                 "COLLATE",
	TK_COMMAND:                 "COMMAND",
	TK_COMMENT:                 "COMMENT",
	TK_COMMIT:                  "COMMIT",
	TK_CONNECT_BY:              "CONNECT_BY",
	TK_CONSTRAINT:              "CONSTRAINT",
	TK_COPY:                    "COPY",
	TK_CREATE:                  "CREATE",
	TK_CROSS:                   "CROSS",
	TK_CUBE:                    "CUBE",
	TK_CURRENT_DATE:            "CURRENT_DATE",
	TK_CURRENT_DATETIME:        "CURRENT_DATETIME",
	TK_CURRENT_SCHEMA:          "CURRENT_SCHEMA",
	TK_CURRENT_TIME:            "CURRENT_TIME",
	TK_CURRENT_TIMESTAMP:       "CURRENT_TIMESTAMP",
	TK_CURRENT_USER:            "CURRENT_USER",
	TK_CURRENT_USER_ID:         "CURRENT_USER_ID",
	TK_CURRENT_ROLE:            "CURRENT_ROLE",
	TK_CURRENT_CATALOG:         "CURRENT_CATALOG",
	TK_DECLARE:                 "DECLARE",
	TK_DEFAULT:                 "DEFAULT",
	TK_DELETE:                  "DELETE",
	TK_DESC:                    "DESC",
	TK_DESCRIBE:                "DESCRIBE",
	TK_DETACH:                  "DETACH",
	TK_DICTIONARY:              "DICTIONARY",
	TK_DISTINCT:                "DISTINCT",
	TK_DISTRIBUTE_BY:           "DISTRIBUTE_BY",
	TK_DIV:                     "DIV",
	TK_DROP:                    "DROP",
	TK_ELSE:                    "ELSE",
	TK_END:                     "END",
	TK_ESCAPE:                  "ESCAPE",
	TK_EXCEPT:                  "EXCEPT",
	TK_EXECUTE:                 "EXECUTE",
	TK_EXISTS:                  "EXISTS",
	TK_FALSE:                   "FALSE",
	TK_FETCH:                   "FETCH",
	TK_FILE:                    "FILE",
	TK_FILE_FORMAT:             "FILE_FORMAT",
	TK_FILTER:                  "FILTER",
	TK_FINAL:                   "FINAL",
	TK_FIRST:                   "FIRST",
	TK_FOR:                     "FOR",
	TK_FORCE:                   "FORCE",
	TK_FOREIGN_KEY:             "FOREIGN_KEY",
	TK_FORMAT:                  "FORMAT",
	TK_FROM:                    "FROM",
	TK_FULL:                    "FULL",
	TK_FUNCTION:                "FUNCTION",
	TK_GET:                     "GET",
	TK_GLOB:                    "GLOB",
	TK_GLOBAL:                  "GLOBAL",
	TK_GRANT:                   "GRANT",
	TK_GROUP_BY:                "GROUP_BY",
	TK_GROUPING_SETS:           "GROUPING_SETS",
	TK_HAVING:                  "HAVING",
	TK_HINT:                    "HINT",
	TK_IGNORE:                  "IGNORE",
	TK_ILIKE:                   "ILIKE",
	TK_IN:                      "IN",
	TK_INDEX:                   "INDEX",
	TK_INDEXED_BY:              "INDEXED_BY",
	TK_INNER:                   "INNER",
	TK_INSERT:                  "INSERT",
	TK_INSTALL:                 "INSTALL",
	TK_INTEGRATION:             "INTEGRATION",
	TK_INTERSECT:               "INTERSECT",
	TK_INTERVAL:                "INTERVAL",
	TK_INTO:                    "INTO",
	TK_INTRODUCER:              "INTRODUCER",
	TK_IRLIKE:                  "IRLIKE",
	TK_IS:                      "IS",
	TK_ISNULL:                  "ISNULL",
	TK_JOIN:                    "JOIN",
	TK_JOIN_MARKER:             "JOIN_MARKER",
	TK_KEEP:                    "KEEP",
	TK_KEY:                     "KEY",
	TK_KILL:                    "KILL",
	TK_LANGUAGE:                "LANGUAGE",
	TK_LATERAL:                 "LATERAL",
	TK_LEFT:                    "LEFT",
	TK_LIKE:                    "LIKE",
	TK_LIMIT:                   "LIMIT",
	TK_LIST:                    "LIST",
	TK_LOAD:                    "LOAD",
	TK_LOCK:                    "LOCK",
	TK_MAP:                     "MAP",
	TK_MATCH:                   "MATCH",
	TK_MATCH_CONDITION:         "MATCH_CONDITION",
	TK_MATCH_RECOGNIZE:         "MATCH_RECOGNIZE",
	TK_MEMBER_OF:               "MEMBER_OF",
	TK_MERGE:                   "MERGE",
	TK_MOD:                     "MOD",
	TK_MODEL:                   "MODEL",
	TK_NATURAL:                 "NATURAL",
	TK_NEXT:                    "NEXT",
	TK_NOTHING:                 "NOTHING",
	TK_NOTNULL:                 "NOTNULL",
	TK_NULL:                    "NULL",
	TK_OBJECT_IDENTIFIER:       "OBJECT_IDENTIFIER",
	TK_OFFSET:                  "OFFSET",
	TK_ON:                      "ON",
	TK_ONLY:                    "ONLY",
	TK_OPERATOR:                "OPERATOR",
	TK_ORDER_BY:                "ORDER_BY",
	TK_ORDER_SIBLINGS_BY:       "ORDER_SIBLINGS_BY",
	TK_ORDERED:                 "ORDERED",
	TK_ORDINALITY:              "ORDINALITY",
	TK_OUT:                     "OUT",
	TK_INOUT:                   "INOUT",
	TK_OUTER:                   "OUTER",
	TK_OVER:                    "OVER",
	TK_OVERLAPS:                "OVERLAPS",
	TK_OVERWRITE:               "OVERWRITE",
	TK_PACKAGE:                 "PACKAGE",
	TK_PARTITION:               "PARTITION",
	TK_PARTITION_BY:            "PARTITION_BY",
	TK_PERCENT:                 "PERCENT",
	TK_PIVOT:                   "PIVOT",
	TK_PLACEHOLDER:             "PLACEHOLDER",
	TK_POLICY:                  "POLICY",
	TK_POOL:                    "POOL",
	TK_POSITIONAL:              "POSITIONAL",
	TK_PRAGMA:                  "PRAGMA",
	TK_PREWHERE:                "PREWHERE",
	TK_PRIMARY_KEY:             "PRIMARY_KEY",
	TK_PROCEDURE:               "PROCEDURE",
	TK_PROPERTIES:              "PROPERTIES",
	TK_PROJECTION:              "PROJECTION",
	TK_PSEUDO_TYPE:             "PSEUDO_TYPE",
	TK_PUT:                     "PUT",
	TK_QUALIFY:                 "QUALIFY",
	TK_QUOTE:                   "QUOTE",
	TK_QDCOLON:                 "QDCOLON",
	TK_RANGE:                   "RANGE",
	TK_RECURSIVE:               "RECURSIVE",
	TK_REFRESH:                 "REFRESH",
	TK_RENAME:                  "RENAME",
	TK_REPLACE:                 "REPLACE",
	TK_RETURNING:               "RETURNING",
	TK_REVOKE:                  "REVOKE",
	TK_REFERENCES:              "REFERENCES",
	TK_RIGHT:                   "RIGHT",
	TK_RLIKE:                   "RLIKE",
	TK_ROLE:                    "ROLE",
	TK_ROLLBACK:                "ROLLBACK",
	TK_ROLLUP:                  "ROLLUP",
	TK_ROW:                     "ROW",
	TK_ROWS:                    "ROWS",
	TK_RULE:                    "RULE",
	TK_SELECT:                  "SELECT",
	TK_SEMI:                    "SEMI",
	TK_SEPARATOR:               "SEPARATOR",
	TK_SEQUENCE:                "SEQUENCE",
	TK_SERDE_PROPERTIES:        "SERDE_PROPERTIES",
	TK_SET:                     "SET",
	TK_SETTINGS:                "SETTINGS",
	TK_SHOW:                    "SHOW",
	TK_SIMILAR_TO:              "SIMILAR_TO",
	TK_SOME:                    "SOME",
	TK_SORT_BY:                 "SORT_BY",
	TK_SOUNDS_LIKE:             "SOUNDS_LIKE",
	TK_SQL_SECURITY:            "SQL_SECURITY",
	TK_START_WITH:              "START_WITH",
	TK_STORAGE_INTEGRATION:     "STORAGE_INTEGRATION",
	TK_STRAIGHT_JOIN:           "STRAIGHT_JOIN",
	TK_STRUCT:                  "STRUCT",
	TK_SUMMARIZE:               "SUMMARIZE",
	TK_TABLE_SAMPLE:            "TABLE_SAMPLE",
	TK_TAG:                     "TAG",
	TK_TEMPORARY:               "TEMPORARY",
	TK_TOP:                     "TOP",
	TK_THEN:                    "THEN",
	TK_TRUE:                    "TRUE",
	TK_TRUNCATE:                "TRUNCATE",
	TK_TRIGGER:                 "TRIGGER",
	TK_TYPE:                    "TYPE",
	TK_UNCACHE:                 "UNCACHE",
	TK_UNDROP:                  "UNDROP",
	TK_UNION:                   "UNION",
	TK_UNNEST:                  "UNNEST",
	TK_UNPIVOT:                 "UNPIVOT",
	TK_UPDATE:                  "UPDATE",
	TK_USE:                     "USE",
	TK_USING:                   "USING",
	TK_VALUES:                  "VALUES",
	TK_VARIADIC:                "VARIADIC",
	TK_VIEW:                    "VIEW",
	TK_SEMANTIC_VIEW:           "SEMANTIC_VIEW",
	TK_VOLATILE:                "VOLATILE",
	TK_VOLUME:                  "VOLUME",
	TK_WHEN:                    "WHEN",
	TK_WHERE:                   "WHERE",
	TK_WINDOW:                  "WINDOW",
	TK_WITH:                    "WITH",
	TK_UNIQUE:                  "UNIQUE",
	TK_UTC_DATE:                "UTC_DATE",
	TK_UTC_TIME:                "UTC_TIME",
	TK_UTC_TIMESTAMP:           "UTC_TIMESTAMP",
	TK_VERSION_SNAPSHOT:        "VERSION_SNAPSHOT",
	TK_TIMESTAMP_SNAPSHOT:      "TIMESTAMP_SNAPSHOT",
	TK_OPTION:                  "OPTION",
	TK_SINK:                    "SINK",
	TK_SOURCE:                  "SOURCE",
	TK_ANALYZE:                 "ANALYZE",
	TK_NAMESPACE:               "NAMESPACE",
	TK_EXPORT:                  "EXPORT",
	TK_HIVE_TOKEN_STREAM:       "HIVE_TOKEN_STREAM",
	TK_SENTINEL:                "SENTINEL",
}
