/* @bruin
name: stripe_stage.invoices
type: bq.sql
description: >
  Conformed invoice facts for billings, current AR, and invoice-line analysis.
  Amounts are native-currency minor units and are not accounting revenue.
  invoice_lines_has_more flags Stripe's paginated embedded line payload; a true
  value means the flattened invoice-line model is not a complete subledger.

materialization:
  type: table

depends:
  - stripe_raw.invoice

tags:
  - stripe_stage
  - stripe
  - billing
  - invoices

columns:
  - name: stripe_invoice_id
    type: STRING
    description: Stripe invoice identifier and natural key.
    primary_key: true
    checks:
      - name: not_null
      - name: unique
  - name: stripe_customer_id
    type: STRING
    description: Stripe billing customer the invoice is billed to.
  - name: invoice_created_at
    type: TIMESTAMP
    description: When the invoice was created in Stripe.
  - name: invoice_due_at
    type: TIMESTAMP
    description: >
      When payment is due. Stripe only sets a due date for invoices collected
      with `send_invoice`, so it is null for automatically charged invoices.
  - name: invoice_finalized_at
    type: TIMESTAMP
    description: >
      When the invoice was finalized, read from Stripe's status transitions. The
      billings report falls back to `invoice_created_at` when it is missing.
  - name: invoice_status
    type: STRING
    description: >
      Stripe invoice status. The billings report excludes `draft` and `void`
      invoices.
  - name: billing_reason
    type: STRING
    description: Why Stripe created the invoice, for example `subscription_cycle`.
  - name: collection_method
    type: STRING
    description: >
      How the invoice is collected, either `charge_automatically` or
      `send_invoice`.
  - name: currency
    type: STRING
    description: Three-letter ISO currency code the invoice is billed in.
  - name: is_live_mode
    type: BOOL
    description: Whether the invoice exists in Stripe live mode.
  - name: is_paid
    type: BOOL
    description: >
      Whether the invoice is currently paid. This is present state, not a
      historical collections measure.
  - name: payment_attempt_count
    type: INT64
    description: Number of payment attempts Stripe has made for the invoice.
  - name: invoice_amount_due_minor
    type: NUMERIC
    description: Amount due in native-currency minor units.
  - name: invoice_amount_paid_minor
    type: NUMERIC
    description: Amount paid in native-currency minor units.
  - name: invoice_amount_remaining_minor
    type: NUMERIC
    description: Amount still owed in native-currency minor units.
  - name: invoice_subtotal_minor
    type: NUMERIC
    description: Subtotal before discounts and taxes, in minor units.
  - name: invoice_total_minor
    type: NUMERIC
    description: >
      Invoice total after discounts and taxes, in minor units. It is the
      billings measure used by `stripe_reports.monthly_invoice_billings`.
  - name: is_subscription_invoice
    type: BOOL
    description: >
      Whether the invoice was generated by a subscription, derived from
      `billing_reason`.
  - name: invoice_lines_has_more
    type: BOOL
    description: >
      Whether Stripe reports more pages in the embedded invoice.lines payload.
      True means invoice_line_items is incomplete; null means the source did
      not provide a parseable pagination indicator.
  - name: invoice_lines
    type: JSON
    description: >
      Embedded Stripe invoice-line payload, flattened by
      `stripe_stage.invoice_line_items`.
@bruin */

SELECT
  id AS stripe_invoice_id,
  customer AS stripe_customer_id,
  TIMESTAMP_SECONDS(SAFE_CAST(created AS INT64)) AS invoice_created_at,
  TIMESTAMP_SECONDS(SAFE_CAST(due_date AS INT64)) AS invoice_due_at,
  TIMESTAMP_SECONDS(SAFE_CAST(
    JSON_VALUE(status_transitions, '$.finalized_at') AS INT64
  )) AS invoice_finalized_at,
  status AS invoice_status,
  billing_reason,
  collection_method,
  currency,
  livemode AS is_live_mode,
  paid AS is_paid,
  SAFE_CAST(attempt_count AS INT64) AS payment_attempt_count,
  SAFE_CAST(amount_due AS NUMERIC) AS invoice_amount_due_minor,
  SAFE_CAST(amount_paid AS NUMERIC) AS invoice_amount_paid_minor,
  SAFE_CAST(amount_remaining AS NUMERIC) AS invoice_amount_remaining_minor,
  SAFE_CAST(subtotal AS NUMERIC) AS invoice_subtotal_minor,
  SAFE_CAST(total AS NUMERIC) AS invoice_total_minor,
  billing_reason IN (
    'subscription_create',
    'subscription_cycle',
    'subscription_update',
    'subscription_threshold'
  ) AS is_subscription_invoice,
  SAFE_CAST(JSON_VALUE(lines, '$.has_more') AS BOOL) AS invoice_lines_has_more,
  lines AS invoice_lines
FROM stripe_raw.invoice;
