name: bruin-init
schedule: dailyadds
start_date: "2023-03-20"

default_connections:
  google_cloud_platform: "alberto-gcp"
  snowflake: "snowflake"
  postgres: "postgres"
  mssql: "mssql"
  synapse: "synapse"
  mongo: "mongo"
  mysql: "some-mysql"
  notion: "some-notion"
  hana: "some-hana"
  shopify: "some-shopify"
  gorgias: "some-gorgias"
  aws: "my-aws"
  klaviyo: "my-klaviyo"
  adjust: "my-adjust"
  facebookads: "my-facebookads"
  stripe: "my-stripe"
  appsflyer: "my-appsflyer"
  kafka: "my-kafka"
  hubspot: "my-hubspot"
  googlesheets: "my-gsheets"
  airtable: "my-airtable"