/* @bruin

type: bq.sql
description: |
  Flattened events table with JSON fields.
  Partitioned by dt, clustered by event_name + user_pseudo_id.
  Thin materialized window over events.stg_events (all parsing logic lives there).

materialization:
  type: table
  strategy: time_interval
  partition_by: dt
  cluster_by:
    - event_name
    - user_pseudo_id
  incremental_key: dt
  time_granularity: date

depends:
  - events.stg_events

columns:
  - name: app
    type: STRING
  - name: platform
    type: STRING
    description: The platform (Android, iOS, Web)
  - name: dt
    type: DATE
    description: The date of the event. It might be different from the ts column, depending on your reporting time zone.
  - name: ts
    type: TIMESTAMP
    description: The timestamp of the event
  - name: user_first_touch_ts
    type: TIMESTAMP
    description: The timestamp of the first touch of the user, collected by Firebase SDK.
  - name: user_pseudo_id
    type: STRING
    description: User ID generated by Firebase. It is not the same as the user_id column.
  - name: user_id
    type: STRING
    description: User ID generated by your app. It is not the same as the user_pseudo_id column.
  - name: event_name
    type: STRING
  - name: app_version
    type: STRING
    description: >
      The cleaned app version, suitable for comparisons like >= or sorting. To standardize the version, we use 3 digits for each part of the version.
      Ex value: 1.20.3 -> 001.020.003
  - name: event_params
    type: STRING
    description: JSON-encoded event parameter map.
  - name: user_properties
    type: STRING
    description: JSON-encoded user properties (excludes user_id and firebase_exp_*/_ltv_*).
  - name: experiments
    type: ARRAY<STRUCT<id INT64, value INT64>>
    description: Active Firebase experiments for the user (extracted from user_properties).
  - name: device
    type: STRING
    description: Device information as JSON
  - name: geo
    type: STRING
    description: Geographic information as JSON
  - name: privacy_info
    type: STRING
    description: Privacy information as JSON
  - name: event_server_timestamp_offset
    type: FLOAT64
    description: The difference between the event timestamp and the server timestamp (milliseconds).
  - name: event_value_in_usd
    type: FLOAT64
    description: The value of the event in USD.

@bruin */

SELECT *
FROM `events.stg_events`
WHERE dt BETWEEN '{{ start_date }}' AND '{{ end_date }}'
