default_environment: default
environments:
  chess-extended:
    connections:
      duckdb:
        - name: "chess-default"
          path: "chess-extended.db"
      chess:
        - name: "chess-default"
          players:
            - "MagnusCarlsen"
            - "Hikaru"
      generic:
        - name: KEY1
          value: value1
  chess-extended-only-checks:
    connections:
      duckdb:
        - name: "chess-default"
          path: "chess-extended-only-checks.db"
      chess:
        - name: "chess-default"
          players:
            - "MagnusCarlsen"
            - "Hikaru"
      generic:
        - name: KEY1
          value: value1
  chess-extended-only-main:
    connections:
      duckdb:
        - name: "chess-default"
          path: "chess-extended-only-main.db"
      chess:
        - name: "chess-default"
          players:
            - "MagnusCarlsen"
            - "Hikaru"
      generic:
        - name: KEY1
          value: value1