# Zoomcamp template: pipeline.yml
# Goal: help you learn Bruin pipeline configuration patterns. This file is intentionally *not* runnable until you complete the TODOs.
#
# Key docs:
# - Pipeline files: https://getbruin.com/docs/bruin/getting-started/pipeline.html
# - Variables (JSON Schema): https://getbruin.com/docs/bruin/getting-started/pipeline-variables.html
# - Run command: https://getbruin.com/docs/bruin/commands/run.html

# TODO: Set a pipeline name (string). This shows up in logs + `BRUIN_PIPELINE` for Python assets.
name: TODO_SET_PIPELINE_NAME

# TODO: Pick a schedule ("daily", "hourly", "weekly", "monthly") or a cron string.
schedule: TODO_SET_SCHEDULE

# TODO: Set the earliest date this pipeline should consider for full refresh backfills.
# Format: YYYY-MM-DD
start_date: "TODO_SET_START_DATE"

# TODO: Configure default connections so assets can omit explicit `connection: ...`.
# Common pattern: `duckdb: duckdb-default` for local dev.
# Docs (connections): https://getbruin.com/docs/bruin/commands/connections.html
default_connections:
  duckdb: TODO_CONNECTION_NAME

# TODO: Define pipeline variables using JSON Schema and defaults.
# Principles:
# - Variables must have a `default` so assets can render without `--var`.
# - In SQL/YAML assets: reference as `{{ var.my_variable }}`.
# - In Python assets: read JSON from env var `BRUIN_VARS`.
#
# Required for this module:
# - Define `taxi_types` (array of strings) with a sensible default.
# - Add one more variable that impacts BOTH ingestion and transformation.
variables:
  taxi_types:
    # TODO: type should be `array` with `items.type: string`
    type: TODO
    items:
      type: TODO
    # TODO: pick a sensible default, e.g. ["yellow", "green"]
    default: TODO

  extra_variable:
    # TODO: define (type + default) and reference it in both Python and SQL assets.
    # Examples: a boolean flag, a list of endpoints, a string "environment", etc.
    type: TODO
    default: TODO

