name: CI Checks

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'resources/**'
      - 'templates/**'
      - 'install.sh'
      - 'README.md'
      - 'Makefile'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'resources/**'
      - 'templates/**'
      - 'install.sh'
      - 'README.md'
      - 'Makefile'
      - 'package.json'
      - 'package-lock.json'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || (github.ref == 'refs/heads/main' && github.sha || github.ref) }}
  cancel-in-progress: true


env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ghcr.io
  IMAGE_NAME: bruin-data/bruin

jobs:
  test:
    strategy:
      matrix:
        platform: [ depot-ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: make test


  end2end:
    strategy:
      matrix:
        platform: [ depot-ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base
      - name: Run integration tests
        run: make integration-test

  dockerBuild:
    runs-on: depot-ubuntu-latest
    name: Docker Build
    permissions:
      # allow issuing OIDC tokens for this workflow run
      id-token: write
      # allow at least reading the repo contents, add other permissions if necessary
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: bruin-data
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Depot
        uses: depot/setup-action@v1

      - name: Build and push Docker image
        uses: depot/build-push-action@v1
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
            BRANCH_NAME=${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

  lint:
    runs-on: depot-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "go.sum"
      - name: Install golangci-lint
        run: |
          VERSION=$(grep '^GOLANGCI_LINT_VERSION=' Makefile | cut -d= -f2)
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${VERSION}
      - name: Run golangci-lint
        run: golangci-lint run --timeout 10m60s ./...

