name: Build Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'package.json'
      - 'package-lock.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js 20.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.0'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run build
        run: npm run docs:build
