name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TELEMETRY_KEY: ${{ secrets.TELEMETRY_KEY }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add GCP_PROJECT_ID --value "$GCP_PROJECT_ID" --repo bruin-data/bruin
          depot ci secrets add GCP_SERVICE_ACCOUNT_JSON --value "$GCP_SERVICE_ACCOUNT_JSON" --repo bruin-data/bruin
          depot ci secrets add GORELEASER_KEY --value "$GORELEASER_KEY" --repo bruin-data/bruin
          depot ci secrets add RELEASE_TOKEN --value "$RELEASE_TOKEN" --repo bruin-data/bruin
          depot ci secrets add TELEMETRY_KEY --value "$TELEMETRY_KEY" --repo bruin-data/bruin
