name: Update Ingestr Version

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for latest ingestr release
        id: check
        run: |
          set -euo pipefail
          latest=$(curl -fsSL https://api.github.com/repos/bruin-data/ingestr/releases/latest | jq -r .tag_name)
          latest=${latest#v}
          current=$(grep -oE 'ingestrVersion\s*=\s*"[^"]+"' pkg/python/uv.go | cut -d '"' -f2)
          echo "current=$current"
          echo "latest=$latest"
          if [ "$latest" != "$current" ]; then
            echo "new=true" >> "$GITHUB_OUTPUT"
            echo "version=$latest" >> "$GITHUB_OUTPUT"
            sed -i -E "s/(ingestrVersion\s*=\s*")[^"]+(\")/\1$latest\2/" pkg/python/uv.go
          else
            echo "new=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.check.outputs.new == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-ingestr-${{ steps.check.outputs.version }}
          commit-message: "chore: bump ingestr to v${{ steps.check.outputs.version }}"
          title: "chore: bump ingestr to v${{ steps.check.outputs.version }}"
          body: "Automated update of ingestr to v${{ steps.check.outputs.version }}"
          delete-branch: true
          labels: automated-update

